<?php

declare(strict_types=1);

/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop by Brand Subscription Functionality Hyva
 */

use Amasty\ShopByBrandSubscriptionFunctionality\ViewModel\BrandInfo;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var Escaper $escaper
 * @var HeroiconsSolid $heroicons
 * @var Template $block
 * @var ViewModelRegistry $viewModels
 */

$heroicons = $viewModels->require(HeroiconsSolid::class);

/** @var BrandInfo $brandInfoViewModel */
$brandInfoViewModel = $block->getData('brand_info_view_model');
?>

<?php if ($brandInfoViewModel->isShow()): ?>
    <div class="ambrand-info flex mb-8 sm:px-0">
        <?= $heroicons->informationCircleHtml('mr-2 fill-blue-500', 24, 24) ?>
        <div class="ambrand-info-values">
            <?php foreach ($brandInfoViewModel->getBrandInfoValues() as $brandInfoValue): ?>
                <p class="ambrand-info-value mb-0"><?= $escaper->escapeHtml($brandInfoValue, ['u', 'b', 'i', 'br', 'a']) ?></p>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
