<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop by Brand Subscription Functionality
 */
/**
 * @var \Amasty\ShopByBrandSubscriptionFunctionality\Block\Widget\BrandInfo $block
 * @var \Magento\Framework\Escaper $escaper
 */

?>
<?php if ($block->isProductPage()): ?>
    <?php foreach ($block->getBrands() as $brand): ?>
        <?php
            $showBrandDescription = $block->shouldShowBrandDescription($brand);
            $showBrandInfo = $block->shouldShowBrandInfo($brand);
        ?>
        <?php if ($showBrandDescription || $showBrandInfo): ?>
            <div class="ambrand-widget-brand-info">
                <span class="ambrand-widget-title"><?= $escaper->escapeHtml(__($brand->getTitle())) ?>:</span>
                <?php if ($showBrandDescription): ?>
                    <p class="ambrand-widget-description"><?= $escaper->escapeHtml(__($brand->getShortDescription()), ['u', 'b', 'i', 'br', 'a']) ?></p>
                <?php endif; ?>
                <?php if ($showBrandInfo): ?>
                    <div class="ambrand-info">
                        <div class="ambrand-info-values">
                            <?php foreach ($block->getBrandInfoValues($brand) as $brandInfoValue): ?>
                                <p class="ambrand-info-value"><?= $escaper->escapeHtml($brandInfoValue, ['u', 'b', 'i', 'br', 'a']) ?></p>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php endif; ?>
                <hr class="ambrand-widget-hr">
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
