<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View;

/** @var View $block */

$product = $block->getProduct();
?>
<section class="text-gray-700 body-font mt-6 lg:mt-0">

    <!-- Product Title -->
    <div class="mb-6">
            <?= $block->getChildHtml('product.title') ?>
    </div>

    <div class="flex pb-6 md:pb-0 lg:flex-row flex-col items-center ">
        <div class="grid grid-rows-auto grid-cols-1 md:gap-x-5 md:grid-cols-[42%_minmax(0,_1fr)] md:grid-rows-[min-content_minmax(0,_1fr)] lg:gap-x-16 lg:grid-cols-2 w-full">

            
            <!-- Product Media -->
            <?= $block->getChildHtml('product.media') ?>

            <!-- Product Info -->
            <?= $block->getChildHtml('product.info') ?>
        </div>
    </div>
</section>



<!-- Product Tabs & Additional Info -->
<section class="mt-8">
    <?= $block->getChildHtml('product_options_wrapper_bottom') ?>
</section>

