<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package GDPR Cookie Hyva Compatibility (System)
 */

use Amasty\GdprCookieHyva\ViewModel\JsLayout;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

$jsLayout = $viewModels->require(JsLayout::class);
?>

<?php foreach ($block->getChildNames() as $buttonName): ?>
    <?php if ($buttonConfig = $jsLayout->getButtonConfig($block->getChildData($buttonName, 'data_js'))): ?>
        <?= /** @noEscape */ $block->getChildBlock($buttonName)->addData($buttonConfig)->toHtml() ?>
    <?php endif; ?>
<?php endforeach; ?>
