<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package GDPR Cookie Hyva Compatibility (System)
 */

use Amasty\GdprCookieHyva\ViewModel\JsLayout;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

$jsLayout = $viewModels->require(JsLayout::class);
$policyText = $jsLayout->getPolicyText();
$isAllowCustomersCloseBar = $jsLayout->isAllowCustomersCloseBar();
?>

<div class="flex flex-col flex-nowrap justify-start h-full text-sm">
   <!--  <div class="flex justify-end">
        <?//php if ($isAllowCustomersCloseBar): ?>
            <button @click="closeCookieBarHandler"
                    aria-label="<?//= $escaper->escapeHtmlAttr(__('Close Cookie Bar')) ?>"
                    class="text-black transition hover:text-red focus:drop-shadow-md hover:drop-shadow-md mt-1 focus:outline-none focus:ring-0"
            >
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 focus:outline-none focus:ring-0" fill="none" viewBox="0 0 24 24"
                     stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/>
                </svg>
            </button>
        <?//php endif; ?>
    </div> -->

    <div class="flex flex-wrap overflow-y-auto ambar-sidebar-group-list mb-3 mt-4 ml-3 pr-2">
        <?php if ($policyText): ?>
            <h3 class="text-lg font-light md:text-[28px] pr-6 ambar-group-title text-ambar-settings-bar-group-title mb-2">Cookies</h3>
            <div id="amcookie-bar-content" class="w-full text-ambar-policy-text py-2">
                <?= $escaper->escapeHtml($policyText, $jsLayout->getAllowedPolicyTextTags()) ?>
            </div>
            <button type="button" x-data="initAmCookieActionDispatcherBtn" data-dispatch-action="cookiebar-action-accept" data-dispatch-payload="{&quot;include_checked_groups&quot;:true}" @click.prevent="actiondispatchHandler" class="ambar-btn-accept ambar-action-btn w-full justify-center mt-2">Save My Cookies And Close</button>
        <?php endif; ?>
        <?= $block->getChildHtml('amasty.cookie.cookiebar.groups') ?>
    </div>

    <div class="flex flex-wrap flex-col mt-auto border-t pt-4">
        

        <div class="flex flex-wrap w-full">
            <?= $block->getChildHtml('amasty.cookie.cookiebar.buttons') ?>
        </div>
    </div>
</div>
