<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php 
$_product = $block->getProduct();

$specialPrice = $_product->getSpecialPrice();
$regularPrice = $_product->getPrice();

$specialFromDate = $_product->getSpecialFromDate();
$specialToDate = $_product->getSpecialToDate();

$newProduct = $_product->getData('new_product'); 

$currentDate = date('Y-m-d');

// Show % OFF label
if ($specialPrice && (!$specialFromDate || $specialFromDate <= $currentDate) && $specialPrice < $regularPrice) {
    $discount = round(100 - ($specialPrice / $regularPrice) * 100);
    echo '<div class="pdp-discount">' . $discount . '%<br>OFF</div>';
}

// Show NEW label 
if ($newProduct !== null && ($newProduct == '1' || strtolower((string)$newProduct) === 'yes')) {
    echo '<div class="pdp-new">New</div>';
}
?>
<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');
    $imageWidth = $block->getImageAttribute('product_page_image_medium', 'width');
    $imageHeight = $block->getImageAttribute('product_page_image_medium', 'height');

?>

<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <img
        alt="main product photo"
        class="gallery-placeholder__image"
        src="<?= /* @noEscape */ $mainImageData ?>"
        <?= $imageWidth ? 'width="'. $escaper->escapeHtmlAttr($imageWidth) .'"' : '' ?>
        <?= $imageHeight ? 'height="'. $escaper->escapeHtmlAttr($imageHeight) .'"' : '' ?>
    />
    <link itemprop="image" href="<?= /* @noEscape */ $mainImageData ?>">
</div>
<?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>
<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>,
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": <?= /* @noEscape */ $block->getGalleryOptions()->getOptionsJson() ?>,
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                 "breakpoints": <?= /* @noEscape */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
