<?php
/** @var \Magento\Checkout\Model\Cart $cart */
$cart = \Magento\Framework\App\ObjectManager::getInstance()
    ->get(\Magento\Checkout\Model\Cart::class);

$quote = $cart->getQuote();
$cartTotal = (float) $quote->getGrandTotal();
?>


<div
    x-data="cartProgress(<?= $cartTotal ?>)"
    class="bg-white"
>
    <!-- Message -->
    <p class="text-black text-sm font-normal md:text-[17px] mb-4">
        <template x-if="remaining > 0">
            
                <span>Spend <strong  class="font-normal text-[#3B7E48]">£<span x-text="remaining.toFixed(2)"></span></strong>
                more to get free shipping. <strong class="hidden" x-text="nextReward"></strong>
            </span>
        </template>

        <template x-if="remaining <= 0">
            <span class="text-green-700 font-semibold">
                🎉 Free Delivery Unlocked!
            </span>
        </template>
    </p>

    

    <!-- Milestones -->
    <div class="flex justify-between mt-3 text-sm lg:text-xl lg:leading-[22px] text-black font-semibold">
        <span :class="isReached(45) ? 'text-green-700' : 'text-black'">
            £45<br><span class="text-black text-sm">5% Discount</span>
        </span>

        <span :class="isReached(75) ? 'text-green-700' : 'text-black'">
            £75<br><span class="text-black text-sm">10% Discount</span>
        </span>

        <span :class="isReached(100) ? 'text-green-700' : 'text-black'">
            £100<br><span class="text-black text-sm">Free Delivery</span>
        </span>
    </div>


<!-- Progress Bar Wrapper -->
<div class="relative w-full mt-4">

    <!-- Bar -->
    <div class="shiping-bar w-full relative">
        <div
            class="shipping-bar-h transition-all duration-500 ease-in-out"
            :style="`width: ${progress}%`">
        </div>
    </div>

    <!-- Moving Van Icon -->
    <div
        class="absolute top-[-18px] transition-all duration-500"
        :style="`left: calc(${progress}% - 12px)`"
    >
        <!-- Van SVG -->
        <svg xmlns="http://www.w3.org/2000/svg"
             class="w-6 h-6 text-green-700 opacity-0"
             fill="currentColor"
             viewBox="0 0 24 24">
            <path d="M3 6h11v8h1.5l2-3H21v5h-1a2 2 0 11-4 0H8a2 2 0 11-4 0H3V6z"/>
        </svg>
        <img src="<?= $block->getViewFileUrl('images/delivery-van-i.svg'); ?>" alt="delivery-van-i" class="absolute w-6 h-6 top-[9px]">
    </div>
</div>

</div>

<script>
function cartProgress(total) {
    const max = 100;

    return {
        total: total,
        progress: Math.min((total / max) * 100, 100),
        remaining: Math.max(max - total, 0),

        nextReward() {
            if (this.total < 45) return '5% Discount';
            if (this.total < 75) return '10% Discount';
            if (this.total < 100) return 'Free Delivery';
            return '';
        },

        isReached(value) {
            return this.total >= value;
        }
    }
}
</script>
