<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentProduct;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var CurrentProduct $currentProduct */
$currentProduct = $viewModels->require(CurrentProduct::class);

/** @var Product $product */
$product = $block->hasData('product')
    ? $block->getData('product')
    : $currentProduct->get();

if (!$product || !$product->getId()) {
    return;
}

$inStock = $product->getIsSalable();
?>
<?php if ($block->getParentBlock()->displayProductStockStatus()): ?>
    <div class="text-center">
        <p
            class="list-out-of-stock w-full
                <?= $inStock ? 'available before:bg-green-500' : 'unavailable before:bg-red-500' ?>"
            title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>"
        ><span class="<?= $escaper->escapeHtmlAttr($inStock ? 'in-stock' : 'out-of-stock text-red') ?>">
    <?= $escaper->escapeHtml($inStock ? __('In stock | Usually dispatched within 24 hours') : __('Out of stock')) ?>
</span>
            
        </p>
    </div>
<?php endif; ?>
