<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Store Locator Hyva Compatibility
 */

$ratingSteps = 5;
$rating = $block->getRating();
$yellowHex = '#f6e05e';
$greyHex = '#cbd5e0';
$starsFilled = is_numeric($rating) ? floor($rating / 100 * $ratingSteps) : 0;
$starFragment = $rating / 100 * $ratingSteps - $starsFilled;
$starsEmpty = floor($ratingSteps - $starsFilled - $starFragment);
?>

<div
    class="amstars-rating-container -small flex"
    title="<?= $escaper->escapeHtml($rating) ?>%"
>
    <span class="sr-only">
        <?= $escaper->escapeJs(__('%1 out of %2 stars', $starsFilled + $starFragment, $ratingSteps)) ?>
    </span>
    <?php $i = 0 ?>
    <?php while ($i < $starsFilled): ?>
        <svg
            xmlns="http://www.w3.org/2000/svg" class="fill-current w-6 h-6" viewBox="3 0 20 20"
            style="color: <?= /** @noEscape */ $yellowHex ?>"
            fill="currentColor"
            aria-hidden="true"
        >
            <path
                d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371
                1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54
                1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1
                1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/>
        </svg>
        <?php $i++; ?>
    <?php endwhile; ?>
    <?php if ($starFragment): ?>
        <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="3 0 20 20"
            fill="currentColor"
            class="w-6 h-6"
            aria-hidden="true"
        >
            <defs>
                <linearGradient id="partialFill">
                    <stop offset="0%" stop-color="<?= /** @noEscape */ $yellowHex ?>"/>
                    <stop offset="<?= $starFragment * 100 ?>%" stop-color="<?= /** @noEscape */ $yellowHex ?>"/>
                    <stop offset="<?= $starFragment * 100 ?>%" stop-color="<?= /** @noEscape */ $greyHex ?>"/>
                    <stop offset="100%" stop-color="<?= /** @noEscape */ $greyHex ?>"/>
                </linearGradient>
            </defs>
            <g fill="url(#partialFill)">
                <path
                    d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969
                    0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54
                    1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1
                    0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"/>
            </g>
        </svg>
    <?php endif; ?>
    <?php $i = 0; ?>
    <?php while ($i < $starsEmpty): ?>
        <svg
            xmlns="http://www.w3.org/2000/svg"
            class="fill-current w-6 h-6"
            style="color: <?= /** @noEscape */ $greyHex ?>"
            viewBox="3 0 20 20"
            fill="currentColor"
            aria-hidden="true"
        >
            <path
                d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0
                1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54
                1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1
                1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
            />
        </svg>
        <?php $i++; ?>
    <?php endwhile; ?>
</div>