<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist\Button;

/** @var Escaper $escaper */
/** @var Button $block */
?>

<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->isSalable()): ?>
    <button type="button"
            @click.prevent="addAllItemsToCart()"
            data-role="all-tocart"
            title="<?= $escaper->escapeHtmlAttr(__('Add All to Cart')) ?>"
            class="w-auto bg-[#3B7E48] hover:bg-[#E63833] group-hover:bg-[#E63833] text-white text-xs  md:text-base  font-normal px-6 py-3 rounded-full transition-all duration-300 uppercase">
        <span><?= $escaper->escapeHtml(__('Add All to Cart')) ?></span>
    </button>
<?php endif;?>
