<?php declare(strict_types=1);

/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop By Hyva Compatibility
 */

use Amasty\Shopby\Block\Navigation\ApplyButton;
use Amasty\Shopby\Block\Navigation\UrlModifier;
use Amasty\ShopbyHyvaCompatibility\ViewModel\ProductListAjax;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;

/** @var ApplyButton $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$uniqueId = uniqid();

/** @var ProductListAjax $productListAjax */
$productListAjax = $viewModels->require(ProductListAjax::class);
$pageLayout = $productListAjax->getPageLayout() ?: $block->getLayout()->getUpdate()->getPageLayout();
$isOneColumn = $pageLayout === '1column' || $pageLayout === 'cms-full-width' || $pageLayout === 'product-full-width';

// phpcs:disable Generic.Files.LineLength.TooLong
?>

<?php if ($block->blockEnabled()): ?>
    <div x-data="dataShowButton_<?= $escaper->escapeHtml($uniqueId) ?>()"
         x-init="initShowButton()"
         x-spread="eventListeners"
         x-bind="eventListeners"
         x-show="showButton"
         style="display: none">
        <?php if (!$block->isAjaxEnabled()): ?>
            <form data-amshopby-filter="">
                <input type="hidden"
                       name="<?= /* @noEscape */ UrlModifier::VAR_REPLACE_URL ?>"
                       value="1"/>
            </form>
        <?php endif; ?>
        <div class="am_shopby_apply_filters bottom-0 md:bottom-auto z-50
            -mt-3 w-full md:w-auto fixed md:absolute md:-mt-4 duration-200 ease-in-out"
            :class="{
                'left-0 md:ml-6 transition-[left,top]': buttonPosition !== 'right',
                'right-0 md:mr-6 transition-[right,top]': buttonPosition === 'right'
            }">
            <div class="am-show-button flex items-center shadow-lg md:rounded-lg bg-white p-2 relative md:justify-start justify-center disabled:opacity-75"> <?php //phpcs:ignore?>
                <svg class="w-4 h-4 text-white fill-current stroke-current absolute -m-4 hidden md:block"
                     :class="{
                         'z-0 bottom-px left-2/4 rotate-90': buttonPosition === 'top',
                         'z-10 left-0 bottom-2/4 translate-y-[-50%] rotate-180': buttonPosition === 'left',
                         'z-10 right-0 bottom-2/4 translate-y-[-50%]': buttonPosition === 'right'
                     }"
                     width="12"
                     height="12">
                    <rect x="0" y="0" width="12" height="12" transform="rotate(45)" class="shadow-xl"/>
                </svg>

                <div class="flex items-center justify-center">
                    <svg width="18"
                         height="18"
                         viewBox="0 0 38 38"
                         xmlns="http://www.w3.org/2000/svg"
                         stroke="#1D4ED8"
                         x-show="!itemsCount"
                         class="mx-4">
                        <g fill="none" fill-rule="evenodd">
                            <g transform="translate(1 1)" stroke-width="2">
                                <circle stroke-opacity=".5" cx="18" cy="18" r="18"/>
                                <path d="M36 18c0-9.94-8.06-18-18-18">
                                    <animateTransform attributeName="transform" type="rotate"
                                                      from="0 18 18" to="360 18 18" dur="1s" repeatCount="indefinite"/>
                                </path>
                            </g>
                        </g>
                    </svg>
                    <span class="am-items font-regular text-gray-900 mx-2 whitespace-nowrap"
                          x-html="itemsCount" x-show="!!itemsCount"></span>
                </div>

                <button amshopby-apply-filter="1"
                        :disabled="disabledButton"
                        :class="{
                            'opacity-75': disabledButton
                        }"
                        id="amasty_shopby_apply_filters_<?= /* @noEscape */ $uniqueId ?>"
                        title="<?= $escaper->escapeHtmlAttr(__('Apply Filters')) ?>"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Apply Filters')) ?>"
                        class="amshopby-button btn btn-primary relative focus:outline-black"
                        @click="applyFilter">
                    <?= $escaper->escapeHtml(__('Apply')) ?>
                </button>
            </div>
        </div>
    </div>
    <script>
        function dataShowButton_<?= $escaper->escapeHtml($uniqueId)?>() {
            return deepMerge({}, dataShowButton(), {
                layout: '<?= $escaper->escapeHtml($pageLayout); ?>',
                clearUrl: '<?= $escaper->escapeUrl($block->getClearUrl()) ?>',
                ajaxEnabled: Boolean(<?= (int)$block->isAjaxSettingEnabled() ?>),
                isOneColumn: Boolean(<?= /** @noEscape */ $isOneColumn; ?>),
                buttonPosition: '<?= $escaper->escapeHtml($block->getButtonPosition()) ?>',
                navigationSelector: '<?= $escaper->escapeHtml($block->getNavigationSelector()) ?>',
            }, initSelectorsILN());
        }
    </script>
<?php endif; ?>
