<div class="nav_right">
    <ul class="custom-links">
        <li>
            <a href="<?= $block->getBaseUrl() ?>sales/order/history/">
                <img src="<?= $block->getViewFileUrl('images/buy-again.svg'); ?>" alt="buy-again" /> Buy Again
            </a>
        </li>
        <li>
            <a href="<?= $block->getBaseUrl() ?>membership-page">
                <img src="<?= $block->getViewFileUrl('images/vip-member.svg'); ?>" alt="vip-member" /> Become a VIP Member
            </a>
        </li>
        <li>
            <a href="<?= $block->getBaseUrl() ?>store-locators">
                <img src="<?= $block->getViewFileUrl('images/store-locator.svg'); ?>" alt="store-locator" /> Store Locator
            </a>
        </li>
    </ul>
</div>
