<div class="franchise-page franchise-page-dekstop">
  <div class="franchise-page">
<div class="tab">
  <button class="tablinks" onclick="openCity(event, '1')" id="defaultOpen">Overview</button>
  <button class="tablinks" onclick="openCity(event, '2')">Our Branches</button>
  <button class="tablinks" onclick="openCity(event, '3')">Why Become A Franchise</button>
  <button class="tablinks" onclick="openCity(event, '4')">What We Look For</button>
  <button class="tablinks" onclick="openCity(event, '5')">Apply Now</button>
  <button class="tablinks" onclick="openCity(event, '6')">FAQs</button>
</div>

<div id="1" class="tabcontent">
  <div class="tabcontent-1">
  <div class="overview-img">
    <img src="<?= $this->getViewFileUrl('images/wholesale-banner.jpg') ?>" alt="wholesale-banner" ></div>
    <h2>Welcome to our Franchise section</h2>
    <div class="overview-img-1"><img src="<?= $this->getViewFileUrl('images/wholesale-img.jpg') ?>" alt="wholesale-img" /></div>
    <p>Do you own a butcher shop or meat outlet, or currently aspire to? Partner with Tariq Halal Meat Wholesalers Ltd. and become a part of our extended family while reaping the many benefits you will experience by associating yourself with our reputable brand. As a Tariq Halal meat franchise, you obtain access to our prestigious Halal suppliers as well as our trustworthy reputation which we have authenticated over the past 45 years while in business. We also provide training on brand awareness to ensure our quality traditions live on.</p>
    <p>Owning a Halal franchise in the UK can be challenging without the correct infrastructure and procurement network. One of the many advantages of partnering with Tariq Halal is the use of our ready-made line of operations, which is meticulously managed from sourcing to delivery. We have put in the hard work so you don’t have to, by eliminating the need for you to identify and organise procurement as well as resolving the question of how you will buy, store, and package your meat. We pride ourselves on our impeccable level of quality control from every step until it reaches the customer, which requires a certain kind of confidence. This is especially true when it comes to the trust we have earned from our customers by asking them to buy fresh meat online.</p>
    <p>Our reputation is based on customer loyalty and yours can be too, through owning a Tariq Halal franchise.</p>
  </div>
</div>

<div id="2" class="tabcontent">
  <div class="tabcontent-1">
  <h2>Our Branches</h2>
    <p>We currently have 10 stores operational with new sites being acquired monthly.</p>
    <p><strong>Please see our current branches:</strong></p>
    <div class="branch-list">
      <ul class="branch-add">
        
        <li class="branch-list-f2"><strong>Cardiff</strong> <br>104-106 Albany Road, Cardiff, CF24 3RT<br> 02920 485 569</li>
        <li><strong>Crawley</strong> <br>33 Queensway, Crawley, RH10 1EG<br>01295 522 189</li>
        <li><strong>Croydon</strong> <br>89 London Road, Croydon, CR0 2RF (Next to LIDL)<br>+44(0) 20 8686 8846</li>
        <li><strong>Finsbury Park</strong> <br>258 Seven Sisters Road, Finsbury Park, London, N4 2HY<br> 0207 281 5450</li>
        <li><strong>Forest Gate</strong> <br>11 Woodgrange Road, Forest Gate, E7 8BA <br>020 8555 6508</li>  
        <li><strong>Fulham</strong> <br>431 North End Road, Fulham Broadway, SW6 1NY<br>+44(0) 20 7381 4252</li>
        <li class="branch-list-f2"><strong>Gerrards Cross</strong> <br>25 Packhorse Road, Gerrards Cross, SL9 7QA<br>017 53 887 271</li>
        <li class="branch-list-f2"><strong>Green Street Branch</strong> <br>252 Green St, London E7 8LF<br>0203 649 5332</li>
        <li class="branch-list-f"><strong>Hammersmith</strong> <br>Istanbul Organic, Tariq Halal Express Counter, 120- 124 King Street, Hammersmith, London, W6 0QT<br>+44(0) 20 8741 6655</li>
        <li class="branch-list-f"><strong>Holborn</strong> <br>183 Drury Lane,
London, WC2B 5QF<br>0207 430 9888</li>
        <li class=""><strong>Hounslow</strong> <br>9 High Street, Hounslow, TW3 1RH<br>+44(0) 20 3302 4330</li>
        <li class=""><strong>Ilford</strong> <br>48 Ilford Lane, Ilford, IG1 2JY<br>+44(0) 20 8911 8201</li>
        <li class="branch-list-f2"><strong>Leyton</strong> <br>794 High Road, Leyton, E10 6AE<br>+44(0) 20 8539 6200</li>
        <li class="branch-list-f2"><strong>Luton</strong> <br>Opening Soon!</li>
        <li><strong>Slough</strong> <br>251 Farnham Road, Slough, SL2 1DE<br>+44(0) 17 5357 1609</li>
        <li><strong>South Harrow</strong> <br>387 Northolt Road, Harrow, HA2 8JD<br>+44(0) 20 8423 4975</li>
        <li><strong>Southall Branch</strong> <br>126 The broadway, Southall, UB1 1QF<br>+44(0) 20 8574 1124</li>
        <li><strong>Southampton</strong> <br>Coming soon<br><br></li>
        
        <li><strong>St Johns Wood</strong> <br>10 Lodge Road, London, NW8 7JA<br>07404 836 538<br><br></li>
        <li class="branch-list-f"><strong>Stratford Shopping Centre</strong> <br>Unit 47/48, The Mall Stratford, Shopping Centre, <br>E15 1XE<br>0204 506 5693</li>
        <li><strong>Streatham</strong> <br>14 Leigham Parade, Streatham Hill, SW16 1DR<br>+44(0) 20 8664 7045</li>
        <li ><strong>Tariq Halal Green Street</strong> <br>252 Green St, London E7 8LF<br>0203 649 5332</li>
        <li class="branch-list-f"><strong>Tariq Supermarket</strong> <br>14 -20 High Street, Wealdstone, HA3 7HA<br>0203 149 8382</li>
        <li class="branch-list-f"><strong>Tariq Halal High Wycombe</strong><br> Al Rizq Supermarket<br>185 Dessborough Road, High Wycombe, HP11 2QN<br>01494 422 280</li>
        <li class=""><strong>Tariq Halal Holborn</strong> <br>183 Drury Lane, London, WC2B 5QF<br>0207 430 9888</li>
        <li ><strong>Tariq Halal Meats Reading</strong> <br>477 Oxford Road, Reading, RG30 1HF <br>0118 956 0664</li>
        <li ><strong>Tariq Halal - Old Kent Road</strong> <br>282 - 286 Old Kent Rd, London SE1 5UE <br>0203 649 7157</li>
        <li ><strong>Tooting</strong> <br>147 Upper Tooting Road, Tooting, SW17 7TJ <br>+44(0) 20 8767 9113</li>
        <li><strong>Wembley (Outlet)</strong> <br>259 Water Road, Wembley, HA0 1HX <br>+44(0) 20 8908 9440</li> <li><strong>Woolwich (SE18)</strong> <br>Coming soon<br><br></li>   
 
      </ul>
    </div>
    </div> 
</div>

<div id="3" class="tabcontent">
  <div class="tabcontent-1">
  <h2>Why Become A Franchise</h2>
    <p><strong>It’s simple. If you can agree to the statements below, then a franchise business is for you!</strong></p>
    <ul>
      <li>Would you like to be your own boss?</li>
<li>Would you like to own your own business?</li>
<li>Would you like to join a successful business model?</li>
<li>Would you like to be part of completely unique franchise?</li>
<li>Would you like to be rewarded for your hard work?</li>

       
    </ul>
    <p><strong>What can you expect as a Tariq Halal meat franchise?</strong></p>
    <ul>
      <li>A supply of a wide variety of fresh, frozen, chilled, and marinated products, including chicken, lamb, turkey, beef and fish</li>
<li>Our products and our business model are tried, tested and proven to succeed, reducing the business risk involved in opening a Halal franchise in UK</li>
<li>Active support and expert advice at every stage of launching your business, from staff recruitment to product promotion and marketing</li>
<li>Special training on food safety compliance, stock control, and equipment procurement, including package deals</li>
<li>We offer ongoing, 'hands-on' assistance at every stage including help identifying the best premise lease deals, if needed</li>
<li>We offer unlimited profit potential. This means, as a new Halal franchise in the UK, excellent profit margins and opportunity await you</li>

       
    </ul>
    <p>We are here to assist you in your achievement. Please enquire today.</p>
    <p>Contact us on 0208 998 4118 or email us at <a href="mailto:info@tariqhalalmeats.com">info@tariqhalalmeats.com</a></p>
  </div>
</div>
<div id="4" class="tabcontent">
  <div class="tabcontent-1">
  <h2>What We Look For</h2>
    <div class="overview-img-1"><img src="<?= $this->getViewFileUrl('images/wholesale-img.jpg') ?>" alt="wholesale-img" /></div>
    <p>To successfully expand, it is crucial that the right people are recruited to work with our team. We are looking for people with the right attitude – you must be prepared to follow an established business model and be flexible as changes arise. Previous business owners are ideal candidates, however we do welcome motivated individuals who possess an attitude to succeed.</p>
    <p>“Your business is our business. We can only succeed together”</p>
  </div>
</div>
<div id="5" class="tabcontent">
  <div class="tabcontent-1">
  <h2>Apply Now</h2>
    <p>Applying to become a franchise is very simple.</p>
    <p>Please complete the following form and someone from our Franchise team will contact you directly.</p>
    <p><strong>They can help with</strong></p>
    <ul>
      <li>Finding site(s)</li>
      <li>Finance with the bank(s)</li>
      <li>Smooth construction of shop</li>
      <li>Access to the best suppliers for shop refits</li>
      <li>And much more….</li>

    </ul>
    <div class="apply-now">
    <form class="form contact contact-us" method="post" action="<?= $this->getUrl('franchise')?>">
    <fieldset class="fieldset ">
  

        <div class="contact-row">
        <div class="field name required">
            
            <div class="control register-field-container">
                <input name="name" id="name" title="Name"
                       value=""
                       class="input-text register-field" type="text" required />

                       <label class="label register-floating-label" for="name">Name</label>
            </div>
        </div>
        <div class="field email required">
            
            <div class="control register-field-container">
                <input name="email" id="email"
                       title="Email"
                       value="" type="text" class="input-text register-field" required />
                       <label class="label register-floating-label" for="email">Email</label>
            </div>
        </div>
         <div class="field telephone">
            
            <div class="control register-field-container">
                <input name="telephone" id="telephone" title="telephone"
                       value="" class="input-text register-field" type="text" required />
                       <label class="label register-floating-label" for="telephone">Phone Number</label>
            </div>
        </div>
        <div class="field phone">
            
            <div class="control register-field-container">
                <input name="BusinessPhone" id="Business-Phone" title="Business Phone"
                       value="" class="input-text register-field" type="text" required />
                       <label class="label register-floating-label" for="Business Phone">Business Phone</label>
            </div>
        </div>
        
      
        <div class="field comment required">
            
            <div class="control register-field-container">
                <textarea name="Address" id="Address" title="" class="input-text register-field" cols="5" rows="3"  required ></textarea>
                <label class="label register-floating-label" for="Address">Address</label>
            </div>
        </div>
        <div class="field Enquiry required">
            
            <div class="control register-field-container">
                <textarea name="Enquiry" id="Enquiry" title="" class="input-text register-field" cols="5" rows="3"  required ></textarea>
                <label class="label register-floating-label" for="Enquiry">Enquiry</label>
            </div>
        </div>
         </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="submit" title="Submit" name="submit" class="action submit primary" value="Submit">
        </div>
    </div>
</form>

<?php 
if(isset($_POST['submit'])){
	//echo "string";exit();
}
?>

</div>
</div>
</div>
<div id="6" class="tabcontent">
  <div class="tabcontent-1">
  <h2>FAQs</h2>

  <div class="faq-list">
    
<div class="accordion-tab">
  <input id="faqtab-r1" type="radio" name="tabr">
<label for="faqtab-r1"><span>Q.&nbsp;</span>Why would I choose Tariq Halal Meats over another franchise</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Tariq Halal Meats represent an innovative breakthrough in the franchise meat market. We offer a unique business opportunity that can be operated in almost all communities across UK. The hours of operation are family orientated and the day-to-day operations are easy to learn and easy to teach. Our dedicated team provides a high level of support to each of our franchisees which reflects in the success of our brand to date.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r2" type="radio" name="tabr">
<label for="faqtab-r2"><span>Q.&nbsp;</span>How much does it cost to acquire a franchise?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Our dedicated franchise team will work with you to estimate costs.</div>
</div>
 
<div class="accordion-tab">
  <input id="faqtab-r3" type="radio" name="tabr">
<label for="faqtab-r3"><span>Q.&nbsp;</span>Where are Tariq Halal Meats franchises available in UK?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Our prioritised location is London, however we are open to suggestions. Please call our team to see if your proposed site is viable. We will conduct a thorough analysis of each proposed site and review them independently. We are currently concentrating our development within London.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r4" type="radio" name="tabr">
<label for="faqtab-r4"><span>Q.&nbsp;</span>Do I need any previous retail or meat cutting experience?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>We do actively seek customers who have previous experience operating their own businesses, however we have a full training programme in place for new franchisees. We will train all approved candidates and offer ongoing training and learning opportunities to ensure that our franchisees are qualified to own and operate a Tariq Halal Meats Franchise location.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r5" type="radio" name="tabr">
<label for="faqtab-r5"><span>Q.&nbsp;</span>What qualities do Tariq Halal Meats look for in its franchisees? </label>
<div class="tab-content"><strong>A.&nbsp;</strong>We look for driven, motivated and charismatic individuals who have people and/ or business management experience. Additionally, we look for financial acumen and the ability to learn as well as teach. Ultimately there needs to be a mutual fit between ourselves and the franchisee regarding corporate culture, brand, and our business ethics and morals.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r6" type="radio" name="tabr">
<label for="faqtab-r6"><span>Q.&nbsp;</span>Is financing available from Tariq Halal Meats?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Tariq Halal Meats does not directly finance our franchisees however we have a qualified commercial manager that can help and assist with any relevant paperwork the bank requires. It is the franchisee candidate’s responsibility to secure financing, and they should undertake due diligence regarding any loans or loan approvals prior to becoming a franchisee.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r7" type="radio" name="tabr">
<label for="faqtab-r7"><span>Q.&nbsp;</span>I don’t have enough money to open a Tariq Halal Meats Franchise but am very motivated. Can you assist me?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Tariq Halal Meats does not directly finance our franchisees, but there are occasions when we have current franchises that are looking to open or invest into additional locations. Providing that the franchisee candidate meets all our other criteria, we will do our best to assist them in partnering with an investor.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r8" type="radio" name="tabr">
<label for="faqtab-r8"><span>Q.&nbsp;</span>How long does the Franchisee agreement last?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>The standard Tariq Halal Meats franchise agreement has a term of 5 years (bespoke agreements can be made depending on individuals)</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r9" type="radio" name="tabr">
<label for="faqtab-r9"><span>Q.&nbsp;</span>What form of training and guidance is provided by Tariq halal meats?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Tariq Halal Meats offers a comprehensive training programme over a period of 30 days which includes one-on-one instruction, study tools, in store training, manuals, testing materials and certification. After successful completion of the training programme, the Tariq Halal Meats store opening team then spends an additional 7 days at the franchisee’s new location. At minimum cost, we provide support and guidance until such time that the franchisee is capable to run their location independently.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r10" type="radio" name="tabr">
<label for="faqtab-r10"><span>Q.&nbsp;</span>Where do I buy supplies?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>All the products are supplied by us. Tariq Halal Meats has partnered with the various abattoirs and supplier companies that will provide approved products to all Tariq Halal Meats Locations across the UK. Every store has access to semi-weekly deliveries, volume discounts, and cold chain management.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r11" type="radio" name="tabr">
<label for="faqtab-r11"><span>Q.&nbsp;</span>Is there a risk to buying a Tariq Halal Meats Franchise?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>All business investments carry a level of risk. Tariq Halal Meats is no different. It is important to carry out due diligence, review all documents, and speak with all relevant individuals including your financial legal advisors prior to making an investment.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r12" type="radio" name="tabr">
<label for="faqtab-r12"><span>Q.&nbsp;</span>How long has Tariq Halal Meats been in business?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Tariq Halal established themselves in 1965. After a successful wholesale business, Tariq Halal opened its first franchise location in 2010 and subsequently opened more soon after. The brand was started primarily as a fresh meat wholesale distributor and butcher shop, and has since expanded to sell fresh, frozen, and dry goods.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r13" type="radio" name="tabr">
<label for="faqtab-r13"><span>Q.&nbsp;</span>Where is Tariq Halal Meats headquarters?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Tariq Halal Meats home office is located at 259 Water Road, Wembley, HA0 1HX</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r14" type="radio" name="tabr">
<label for="faqtab-r14"><span>Q.&nbsp;</span>How many Tariq Halal Meats stores are in operation, and where are they located?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Please visit our website for a complete and up to date list of our locations: www.tariqhalalmeats.com</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r15" type="radio" name="tabr">
<label for="faqtab-r15"><span>Q.&nbsp;</span>Who owns Tariq Halal Meats? Is it a public or private company?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Tariq Halal is a privately held company based in Wembley, London that specialises in franchise branding and growth</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r16" type="radio" name="tabr">
<label for="faqtab-r16"><span>Q.&nbsp;</span>What experience does the leadership team at Tariq halal meats have in growing and operating a franchise system?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Our leadership team has direct franchise experience with some of the latest corporations in the UK. They have held director level positions overseeing franchise development real estate, construction and purchasing, marketing, accounting, and operations departments. They hold advanced degrees and designations that are relevant to the business of operating a successful franchise system.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r17" type="radio" name="tabr">
<label for="faqtab-r17"><span>Q.&nbsp;</span>Can I open more than one Tariq halal meats location?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Yes. Tariq Halal Meats’ business model has been designed to allow franchisees to own and operate multiple locations. Franchisees must first demonstrate operational and financial success prior to opening subsequent locations. In addition, Tariq Halal Meats may require specific multi-store training for franchisees seeking to open more than one location.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r18" type="radio" name="tabr">
<label for="faqtab-r18"><span>Q.&nbsp;</span>What is your ongoing royalty fee?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>There is no royalty fee only a Franchise Fee (initial) of £40,000 + VAT</div>
 
</div>

<div class="accordion-tab">
  <input id="faqtab-r19" type="radio" name="tabr">
<label for="faqtab-r19"><span>Q.&nbsp;</span>What is the ongoing advertising fee?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>The current advertising fee is monthly min £1000 + VAT depending on the size and location.</div>
</div>


<div class="accordion-tab">
  <input id="faqtab-r20" type="radio" name="tabr">
<label for="faqtab-r20"><span>Q.&nbsp;</span>What is the average size of a Tariq Halal Meats retail store?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Tariq Halal Meats locations are min 1600- 3000 sqft on average.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r21" type="radio" name="tabr">
<label for="faqtab-r21"><span>Q.&nbsp;</span>What are Tariq Halal Meats’ typical hours of operations?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>All Tariq Halal Meats locations operate daily from 8am-10pm</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r22" type="radio" name="tabr">
<label for="faqtab-r22"><span>Q.&nbsp;</span>How much money can I make with a Tariq Halal Meats Franchise?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Profitability depends on a number of factors. It is important to note that personal abilities, location and fiscal management amongst many other considerations will positively or negatively impact all business models and a Tariq Halal Meats Ltd Franchise is no different. In depth information regarding profit potential will be provided to you when you meet with Tariq Halal Meats Ltd.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r23" type="radio" name="tabr">
<label for="faqtab-r23"><span>Q.&nbsp;</span>How long does it take to open a new Tariq halal meats franchise?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>It typically takes 6-12 months to open a new location</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r24" type="radio" name="tabr">
<label for="faqtab-r24"><span>Q.&nbsp;</span>Can I build my own store?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>No. Tariq Halal Meats provides a turn-key construction service through the provision of a project management team. We have found that our franchisee’s financial interests are better served learning the business of Tariq Halal Meats versus the business of construction.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r25" type="radio" name="tabr">
<label for="faqtab-r25"><span>Q.&nbsp;</span>Can my friend or family do the electrical/plumbing/dry wall etc.?</label>
<div class="tab-content"><strong>A.&nbsp;</strong><strong>We are open to reviewing all trade references and passing them on to the local general contractor for consideration</strong> <br> Provided the trades are all able to meet budgets, timing and quality of workmanship we will do our best to ensure they are in the construction process.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r26" type="radio" name="tabr">
<label for="faqtab-r26"><span>Q.&nbsp;</span>Are there sites available in my area?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Upon reviewing your application, Tariq Halal Meats will research available sites in your area and provide you with an answer.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r27" type="radio" name="tabr">
<label for="faqtab-r27"><span>Q.&nbsp;</span>Does Tariq Halal Meats provide franchise support?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Yes. We provide valuable support in the following areas; training, site selection, construction, store design/equipment, store opening, operations and marketing.</div>
</div>


<div class="accordion-tab">
  <input id="faqtab-r28" type="radio" name="tabr">
<label for="faqtab-r28"><span>Q.&nbsp;</span>Is Tariq Halal an equal opportunity franchisor?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Yes, Tariq Halal Meats is committed to providing equal opportunities for all interested candidates across the UK. Our interests are tied to the success of our franchisees and we act accordingly.</div>
</div>


<div class="accordion-tab">
  <input id="faqtab-r29" type="radio" name="tabr">
<label for="faqtab-r29"><span>Q.&nbsp;</span>How does Tariq Halal Meats spend the advertising fees collected from each location?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Tariq Halal Meats spends 100% of the advertising fees collected in store marketing (print and video), as well as website and local marketing initiatives utilising modalities such as print and radio. Franchises are expected to allocate a percentage of sales for additional local store marketing that they personally direct.</div>
</div>
 

<div class="accordion-tab">
  <input id="faqtab-r30" type="radio" name="tabr">
<label for="faqtab-r30"><span>Q.&nbsp;</span>Can I convert my current butcher shop into Tariq halal franchise?</label>
<div class="tab-content"><strong>A.&nbsp;</strong>Yes, of course you can. We would be happy to work with you on managing the A-Z of the project and treat the new conversion as any Tariq Halal Franchise.</div>
 
</div>

  </div>
</div>
</div>
</div>
</div>

<script>
function openCity(evt, cityName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " active";
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>
