<?php
/**
 * Copyright © 2015 ebizmarts. All rights reserved.
 * See LICENSE.txt for license details.
 */

$_code = $block->getMethodCode();

?>

<div id="payment_form_<?= $block->escapeHtmlAttr($_code) ?>" class="admin__page-section-item" style="display:none;"
     data-mage-init='{"sagepaysuiteFormForm":{"serviceUrl":"
        <?= $block->escapeHtml($block->getUrl('sagepaysuite/form/request', [])); ?>"}}'>

    <span id="<?= $block->escapeHtmlAttr($_code) ?>-payment-errors" class="message error" style="display: none;"></span>

    <img style="margin-top: 10px; max-height: 45px;" 
    class="payment-icon sagepaysuite-payment-icon" src="https://www.sagepay.co.uk/files/logo_0.png"/>

    <div class="message message-warning warning">
        <p><?= $block->escapeHtml(__("This integration is deprecated and will be removed on the next release.")) ?></p>
        <p><?= $block->escapeHtml(__("Please use Direct with DropIn interface.")) ?></p>
    </div>

    <div class="payment-method-note">
        <strong><?= $block->escapeHtml(__("You will be redirected to Opayo to complete payment.")) ?></strong>
    </div>

    <!-- #### sagepay form request form #### -->
    <form
        data-bind="attr: {id: getCode() + '-form'}"
        style="display:none;"
        method="POST"
        action="">
        <input type="hidden" name="VPSProtocol" value=""/>
        <input type="hidden" name="TxType" value=""/>
        <input type="hidden" name="Vendor" value=""/>
        <input type="hidden" name="Crypt" value=""/>
    </form>
</div>