<?php
/**
 * Copyright © 2015 ebizmarts. All rights reserved.
 * See LICENSE.txt for license details.
 */

$_code   = $block->escapeHtml($block->getMethodCode());

// phpcs:disable
/** @var \Ebizmarts\SagePaySuite\Model\Config $_config */
$_config = $this->helper('Ebizmarts\SagePaySuite\Helper\Data')->getSagePayConfig();
// phpcs:enable
$_config->setMethodCode($block->getMethodCode());

$storeId = $block->getBackendSession()->getStoreId();
$_config->setConfigurationScopeId($storeId);

$_config->setConfigurationScope(\Magento\Store\Model\ScopeInterface::SCOPE_STORE);

$dropInEnabled = $_config->dropInEnabled();
?>
<div id="payment_form_<?= $block->escapeHtmlAttr($_code) ?>" class="admin__page-section-item" style="display:none;"
    data-mage-init='{"sagepaysuitepimotoCcForm":{
                            "url": {
                                "generateMerchantKey":"<?=
                                $block->escapeHtml($block->getUrl('sagepaysuite/pimoto/generateMerchantKey', []));
                                ?>",
                                "request":"<?= $block->escapeHtml(
                                    $block->getUrl('sagepaysuite/pimoto/request', [])
                                ); ?>"
                            },
                            "mode":"<?= $block->escapeHtml($_config->getMode()); ?>",
                            "dropin":"<?= $block->escapeHtml((int)$dropInEnabled); ?>"
                        }
                    , "validation":{}}'>

    <div id="<?= $block->escapeHtmlAttr($_code) ?>-info-message" class="message message-info info">
        <div>
            <div id="sagepaysuite-info-message1">
                <p><b>Important Security Notice</b></p>
                <p>
                    Taking credit card numbers over the phone or through non-secure channels and entering them into the
                    <b>Magento backend</b> is
                    <b>not PCI compliant</b>
                </p>
                <p>
                    For secure MOTO orders, please
                    <a href="mailto:support@ebizmarts-desk.zendesk.com?subject=Secure MOTO Payments">Contact us</a>.
                    <br>Your security matters.
                </p>
            </div>
            <div id="sagepaysuite-info-message2">
                <p><b>Important Security Notice</b></p>
                <p>Our priority is your security. Please be aware that the traditional method of recording
                    credit card numbers over the phone, using shared computers,
                    or jotting down card details for later entry into the Magento backend is
                    <b>not a secure way to process MOTO orders.</b>
                </p>
                <p>
                    For a more secure and compliant MOTO order process, we encourage you to
                    <a href="mailto:support@ebizmarts-desk.zendesk.com?subject=Secure MOTO Payments">
                        get in touch with us.
                    </a>
                    We're here to help you safeguard your transactions and personal information.
                </p>
            </div>
        </div>
    </div>
    <span id="<?= $block->escapeHtmlAttr($_code) ?>-payment-errors" class="message error" style="display: none;"></span>

    <?php if ($dropInEnabled): ?>
        <div id="sp-container"></div>
        <div id="submit-container">
            <div class="actions-toolbar">
                <div class="primary">
                    <button class="action primary checkout" style="display:none;"
                     id="submit_dropin_payment" type="button">
                        <span><?= $block->escapeHtml(__('Submit payment')); ?></span>
                    </button>
                </div>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <p id="dropin_start_lbl">
                    <?=
                    $block->escapeHtml(__("Please click on Submit Order to load the secure credit card form."));
                    ?>
                </p>
            </div>
        </div>
    <?php else: ?>
        <fieldset class="admin__fieldset">
            <div class="admin__field">
                <label class="label admin__field-label" for="<?= $block->escapeHtmlAttr($_code) ?>_cardholder">
                <?= $block->escapeHtml(__('Card Holder Name')) ?><span class="required">*</span></label>
                <div class="admin__field-control control">
                    <input type="text" id="<?= $block->escapeHtmlAttr($_code) ?>_cardholder"
                    title="<?= $block->escapeHtml(__('Card Holder Name')) ?>"
                    class="required-entry input-text admin__control-text" autocomplete="off" value="" />
                </div>
            </div>
        </fieldset>
        <fieldset class="admin__fieldset">
            <div class="admin__field">
                <label class="label admin__field-label" for="<?= $block->escapeHtmlAttr($_code) ?>_cc_number">
                <?= $block->escapeHtml(__('Credit Card Number')) ?><span class="required">*</span></label>
                <div class="admin__field-control control">
                    <input data-validate="{required:true, 'validate-cc-number':true}" type="number"
                    id="<?= $block->escapeHtmlAttr($_code) ?>_cc_number"
                    title="<?= $block->escapeHtmlAttr(__('Credit Card Number')) ?>"
                class="validate-digits required-entry no-whitespace input-text admin__control-text validate-cc-number"
                    autocomplete="off" value="" />
                </div>
            </div>
        </fieldset>
        <fieldset class="admin__fieldset">
            <div id="<?= $block->escapeHtmlAttr($_code) ?>_cc_type_exp_div" class="admin__field">
                <label class="label admin__field-label" for="<?= $block->escapeHtmlAttr($_code) ?>_expiration" >
                <?= $block->escapeHtml(__('Expiration Date')) ?><span class="required">*</span></label>
                <div class="admin__field-control control">
                    <select data-validate='{"required":true}' id="<?= $block->escapeHtmlAttr($_code) ?>_expiration"
                    class="required-entry month validate-cc-exp required-entry _required select admin__control-select">
                        <?php $_ccExpMonth = $block->getInfoData('cc_exp_month') ?>
                        <?php foreach ($block->getCcMonths() as $k => $v): ?>
                            <option value="<?= $block->escapeHtmlAttr($k ? $k : '') ?>"<?php if ($k==$_ccExpMonth):
                                ?> selected="selected"<?php
                                           endif ?>><?= $block->escapeHtml($v) ?></option>
                        <?php endforeach ?>
                    </select>
                    <?php $_ccExpYear = $block->getInfoData('cc_exp_year') ?>
                    <select data-validate='{"required-entry":true}'
                    id="<?= $block->escapeHtmlAttr($_code) ?>_expiration_yr"
                    class="year required-entry _required select admin__control-select">
                        <?php foreach ($block->getCcYears() as $k => $v): ?>
                            <option value="<?= $block->escapeHtmlAttr($k ? $k : '') ?>"<?php if ($k==$_ccExpYear):
                                ?> selected="selected"<?php
                                           endif ?>><?= $block->escapeHtml($v) ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
        </fieldset>

        <?php if ($block->hasVerification()): ?>
            <fieldset class="admin__fieldset hide_if_token_selected">
                <div id="<?= $block->escapeHtmlAttr($_code) ?>_cc_type_cvv_div" class="admin__field">
                    <label class="label admin__field-label" for="<?= $block->escapeHtmlAttr($_code) ?>_cc_cid" >
                    <?= $block->escapeHtml(__('Card Verification Number')) ?><span class="required">*</span></label>
                    <div class="admin__field-control control">
                        <div class="v-fix">
                            <input data-validate='{"required-number":true}' type="text"
                            title="<?= $block->escapeHtmlAttr(__('Card Verification Number')) ?>"
                            class="admin__control-text input-text cvv required-entry"
                            id="<?= $block->escapeHtmlAttr($_code) ?>_cc_cid" value="" />
                        </div>
                    </div>
                </div>
            </fieldset>
        <?php endif; ?>
    <?php endif; ?>
</div>
