<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Customer\Block\Address\Grid;
use Magento\Framework\Escaper;

/** @var Grid $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<div class="block block-addresses-list bg-[#F5F9F7] py-4 md:pb-8 px-2 md:px-8 md:mt-0">
    <div class="block-title text-2xl mb-6 px-4 md:px-0">
        <?= $escaper->escapeHtml(__('Address Book')) ?>
    </div>
    <div class="block-content md:bg-white px-2 md:px-0 mx-0" x-data="initAddresses()">
        <?php if ($additionalAddresses = $block->getAdditionalAddresses()): ?>
            <div class="grid grid-cols-1 lg:grid-cols-6 my-6">
                <div class="hidden lg:block p-2 bg-[#E4F0E8] text-base text-black font-bold">
                    <?= $escaper->escapeHtml(__('Company')) ?>
                </div>
                <div class="hidden lg:block p-2 bg-[#E4F0E8] text-base text-black font-bold">
                    <?= $escaper->escapeHtml(__('Name')) ?>
                </div>
                <div class="hidden lg:block p-2 bg-[#E4F0E8] text-base text-black font-bold">
                    <?= $escaper->escapeHtml(__('Street Address')) ?>
                </div>
                <div class="hidden lg:block p-2 bg-[#E4F0E8] text-base text-black font-bold">
                    <?= $escaper->escapeHtml(__('City')) ?>
                </div>
                <div class="hidden lg:block p-2 bg-[#E4F0E8] text-base text-black font-bold">
                    <?= $escaper->escapeHtml(__('Country')) ?>
                </div>
                <div class="hidden lg:block p-2 bg-[#E4F0E8] text-base text-black font-bold"></div>
                <?php $i = 0; ?>
                <?php foreach ($additionalAddresses as $address): ?>
                    <?php $i++ ?>
                    <div class="px-0 py-2 md:p-2 <?= $i % 2 === 0 ? '' : ' ' ?>">
                        <span class="md:hidden  font-bold text-base">Company : </span>
                        <?= $escaper->escapeHtml($address->getCompany()) ?>
                    </div>
                    <div class="px-0 py-2 md:p-2 <?= $i % 2 === 0 ? '' : ' ' ?>">
                        <span class="md:hidden  font-bold text-base">Name : </span>
                        <?= $escaper->escapeHtml($address->getLastname()) ?>,
                        <?= $escaper->escapeHtml($address->getFirstname()) ?>
                    </div>
                    <div class="px-0 py-2 md:p-2 <?= $i % 2 === 0 ? '' : ' ' ?>">
                        <span class="md:hidden  font-bold text-base">Street Address : </span>
                        <?= $escaper->escapeHtml($block->getStreetAddress($address)) ?>
                    </div>
                    <div class="px-0 py-2 md:p-2 <?= $i % 2 === 0 ? '' : ' ' ?>">
                        <span class="md:hidden  font-bold text-base">City : </span>
                        <?= $escaper->escapeHtml($address->getCity()) ?>
                    </div>
                    <div class="px-0 py-2 md:p-2 <?= $i % 2 === 0 ? '' : ' ' ?>">
                        <span class="md:hidden font-bold text-base">Country : </span>
                        <?= $escaper->escapeHtml($block->getCountryByCode($address->getCountryId())) ?>
                    </div>
                    <div class="px-0 py-2 md:p-2 action-box <?= $i % 2 === 0 ? '' : ' ' ?>">
                        <a class="action edit inline-block text-sm underline text-secondary-darker"
                            title="<?= $escaper->escapeHtmlAttr(__('Edit')) ?>"
                            href="<?= $escaper->escapeUrl($block->getUrl(
                                'customer/address/edit',
                                ['id' => $address->getId()]
                            )) ?>">
                            <?= $heroicons->pencilAltHtml('', 24, 24, ['aria-hidden' => true]); ?>
                            <span></span>
                        </a>
                        <a class="action delete ml-2 inline-block text-sm underline text-secondary-darker"
                           title="<?= $escaper->escapeHtmlAttr(__('Delete')) ?>"
                           @click.prevent="deleteAddressById(<?= $escaper->escapeJs($address->getId()) ?>)" href="#">
                            <?= $heroicons->trashHtml('', 24, 24, ['aria-hidden' => true]); ?>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
            <?php if ($block->getChildHtml('pager')): ?>
                <div class="customer-addresses-toolbar toolbar bottom px-2 pb-4">
                    <?= $block->getChildHtml('pager') ?>
                </div>
            <?php endif; ?>

        <?php else: ?>
            <p class="empty">
                <?= $escaper->escapeHtml(__('You have no other address entries in your address book.')) ?>
            </p>
        <?php endif ?>

        <script>
            function initAddresses() {
                return {
                    deleteAddressById(id) {
                        if (window.confirm(
                            '<?= $escaper->escapeJs(__('Are you sure you want to delete this address?')) ?>'
                        )) {
                            hyva.postForm(
                                {
                                    "action": '<?= $escaper->escapeJs($block->getDeleteUrl()) ?>',
                                    "data": {
                                        "id": id
                                    }
                                }
                            );
                        }
                    }
                }
            }
        </script>
    </div>
</div>

<div class="actions-toolbar pt-6 pb-20 !border-0">
     
        <a href="<?= $escaper->escapeUrl($block->getUrl('customer/address/new')) ?>"
           class="bg-[#3B7E48] hover:bg-[#E63833] group-hover:bg-[#E63833] text-white text-xs  md:text-base font-normal px-2 py-3 rounded-full transition duration-400 uppercase px-8 order-1">
            <span>
                <?= $escaper->escapeHtml(__('Add New Address')) ?>
            </span>
        </a>
     
        <a class="text-black underline text-xs  md:text-base font-normal px-2 py-3 rounded-full transition duration-400 uppercase px-0"
           href="<?= $escaper->escapeUrl($block->getUrl('customer/account')) ?>">
            <span>
                <?= $escaper->escapeHtml(__('Back')) ?>
            </span>
        </a>
     
</div>
