<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Advanced Search Hyva Compatibility M2 by Amasty
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
// phpcs:disable Generic.Files.LineLength.TooLong
?>

<div class="w-full mb-6 am-search-item-list" data-amsearch-analytics="block">
    <a href="#amasty_xsearch_bestsellers_slider_end"
       class="action skip sr-only focus:not-sr-only focus:absolute focus:z-30 focus:bg-white">
        <?= $escaper->escapeHtml(__('Press to skip carousel')) ?>
    </a>
    <h3 class="text-lg font-bold mb-2" x-text="bestsellersTitle"></h3>
    <div class="w-full carousel" x-ref="bestsellersContainer">
        <div
            class="relative w-full overflow-x-hidden carousel"
            x-intersect:enter.once="bestsellersEnterOnceEvent"
            x-on:resize.window.debounce="bestsellersResizeWindowEvent"
        >
            <div
                class="relative flex flex-nowrap w-full overflow-x-auto carousel-slides snap"
                @scroll.debounce="bestsellersScrollEvent"
                id="bestsellerSlider"
            >
                <template x-for="(product, index) in bestsellersItems" :key="index">
                    <div class="carousel-slide flex flex-shrink-0 w-full js_slide md:w-1/2 lg:w-1/3 xl:w-1/4 h-carousel-product-item">
                        <?= /** @noEscape  */ $block->fetchView(
                            $block->getTemplateFile(
                                'Amasty_XsearchHyvaCompatibility::header-search/components/product-slider-item.phtml'
                            )
                        ) ?>
                    </div>
                </template>
            </div>
            <div class="carousel-controls">
                <div style="min-height: 65px">
                    <template x-if="isBestsellersPages">
                        <div class="flex items-center justify-center py-4">
                            <button
                                aria-label="<?= $escaper->escapeHtml(__('Previous')) ?>"
                                class="mr-4 text-black rounded-full flex-none"
                                :class="bestsellersPreviousClass"
                                @click="bestsellersPreviousEvent"
                                @keydown.enter.prevent.stop="bestsellersPreviousEvent"
                                @keydown.space.prevent.stop="bestsellersPreviousEvent"
                            >
                                <?= $heroicons->chevronLeftHtml("w-5 h-5", 25, 25) ?>
                            </button>

                            <div class="flex flex-wrap w-full md:w-auto justify-center">
                                <template x-for="(item, index) in bestsellersItemCount" :key="index">
                                    <span
                                        role="button"
                                        tabindex="0"
                                        class="flex-shrink-0 block w-3 h-3 m-1 bg-black rounded-full shadow cursor-pointer"
                                        :class="bestsellersGoToItemClass"
                                        :aria-label="bestsellersGoToItemAriaLabel"
                                        data-label="<?= $escaper->escapeHtmlAttr(__('Go to item')) ?>"
                                        @click="bestsellersGoToItemEvent"
                                        @keydown.enter.prevent.stop="bestsellersGoToItemEvent"
                                        @keydown.space.prevent.stop="bestsellersGoToItemEvent"
                                    ></span>
                                </template>
                            </div>

                            <button
                                aria-label="<?= $escaper->escapeHtml(__('Next')) ?>"
                                class="ml-4 text-black rounded-full flex-none"
                                :class="bestsellersNextClass"
                                @click="bestsellersNextEvent"
                                @keydown.enter.prevent.stop="bestsellersNextEvent"
                                @keydown.space.prevent.stop="bestsellersNextEvent"
                            >
                                <?= $heroicons->chevronRightHtml("w-5 h-5", 25, 25) ?>
                            </button>
                        </div>
                    </template>
                </div>
            </div>
            <span id="amasty_xsearch_bestsellers_slider_end" tabindex="-1"></span>
        </div>
    </div>
</div>
