<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Advanced Search Hyva Compatibility M2 by Amasty
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>
<div class="w-full mb-6 am-search-item-list" data-amsearch-analytics="block">
    <h3 class="text-lg font-bold mb-2 px-4" x-text="brandTitle"></h3>

    <template x-for="(item, index) in brandItems" :key="index">
        <a
            class="w-full block hover:bg-gray-100 py-2 px-4"
            :href="brandItemUrl"
            x-html="brandItemName"
        ></a>
    </template>
</div>
