<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Advanced Search Hyva Compatibility M2 by Amasty
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>
<div class="w-full mb-6 mt-6 md:mt-2 am-search-item-list" data-amsearch-analytics="block">
    <h3 class="text-xl font-bold mb-2 px-2" x-text="categoryTitle"></h3>

    <template x-for="(item, index) in categoryItems" :key="index">
        <div class="pb-4 mb-0">
            <a
                class="w-full block text-base hover:bg-gray-100 py-1 px-2"
                :href="categoryItemUrl"
            >
                <span x-html="categoryItemName" class="font-bold"></span>
            </a>
            <span
                class="text-black text-base block mt-1 px-2"
                x-html="categoryItemDescription"
                x-show="categoryItemDescription"
            ></span>
        </div>
    </template>
</div>
