<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Advanced Search Hyva Compatibility M2 by Amasty
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>
<div class="w-full mb-6 am-search-item-list">
    <h3
        class="text-xl text-black font-bold mb-2 px-4"
        x-text="recentSearchesTitle"
    ></h3>
    <span class="block w-10 h-0.5 bg-red-600 mt-3 mb-3 ml-4"></span>

    <div class="flex direction-row flex-wrap mx-4">
        <template x-for="(searchItem, index) in recentSearchesItems" :key="index">
            <a
                class="w-full block hover:bg-gray-100 py-1 px-0 text-black text-base hover:text-red-600 transition duration-300 capitalize"
                :href="recentSearchesLink"
                x-html="recentSearchesItemName"
            ></a>
        </template>
    </div>
</div>
