<section class="franchise-tab-sec w-full px-0 py-10">
  <div class="container">
  <div class="grid grid-cols-1 md:grid-cols-[280px_1fr] gap-8">
        <!-- TABS -->
    <div
      class="flex md:flex-col overflow-x-auto text-sm lg:text-base md:overflow-visible border-b md:border-b-0 md:border-r"
    >
      <button
        class="tab-btn active"
        data-tab="overview"
      >Overview</button>

      <button class="tab-btn" data-tab="branches">Our Branches</button>
      <button class="tab-btn" data-tab="why">Why Become A Franchise</button>
      <button class="tab-btn" data-tab="look">What We Look For</button>
      <button class="tab-btn" data-tab="apply">Apply Now</button>
      <button class="tab-btn" data-tab="faq">FAQs</button>
      <a class="md:bg-[url('/pub/media/wysiwyg/drive-thu-icon.svg')] 
       bg-no-repeat 
       bg-[center_right] 
       text-black 
       no-underline 
       inline-block 
       w-full" href="<?php echo $block->getBaseUrl().'drive-thru'; ?>"><button class="tab-btn" data-tab="drive">Drive-Thru</button></a>
    </div>

        <!-- CONTENT -->
    <div class="bg-[#fdeeee] px-6 py-6">
      <div id="overview" class="tab-content active">
         
    <div class="mb-8">
      <img
        src="/media/wysiwyg/wholesale-banner.jpg"
        alt="Franchise Team"
        class="w-full h-auto object-cover"
      />
    </div>
 
    <div class="grid grid-cols-1">
     
      <div>
        <h2 class="text-xl md:text-2xl font-semibold mb-4">
          Welcome to our Franchise section
        </h2>

        <p class="text-sm md:text-base text-black leading-relaxed mb-4">
          Do you own a butcher shop or meat outlet, or currently aspire to? Partner with Tariq Halal Meat Wholesalers Ltd. and become a part of our extended family while reaping the many benefits you will experience by associating yourself with our reputable brand. As a Tariq Halal meat franchise, you obtain access to our prestigious Halal suppliers as well as our trustworthy reputation which we have authenticated over the past 45 years while in business. We also provide training on brand awareness to ensure our quality traditions live on.
        </p>

        <p class="text-sm md:text-base text-black leading-relaxed mb-4">
          Owning a Halal franchise in the UK can be challenging without the correct infrastructure and procurement network. One of the many advantages of partnering with Tariq Halal is the use of our ready-made line of operations, which is meticulously managed from sourcing to delivery. We have put in the hard work so you don’t have to, by eliminating the need for you to identify and organise procurement as well as resolving the question of how you will buy, store, and package your meat. We pride ourselves on our impeccable level of quality control from every step until it reaches the customer, which requires a certain kind of confidence. This is especially true when it comes to the trust we have earned from our customers by asking them to buy fresh meat online.
        </p>

        <p class="text-sm md:text-base text-black leading-relaxed mb-4">Our reputation is based on customer loyalty and yours can be too, through owning a Tariq Halal franchise.</p>
      </div>
 
  </div>
 

      </div>

      <div id="branches" class="tab-content">
        <h2 class="text-xl md:text-2xl font-semibold mb-2">
      Our Branches
    </h2>

    <p class="text-sm md:text-base text-gray-700 mb-2">
      We currently have 10 stores operational with new sites being acquired monthly.
    </p>

    <p class="text-sm md:text-base font-semibold mb-6">
      Please see our current branches:
    </p>
 
    <ul
      class="branch-list grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4"
    >
 
       <li><strong>Cardiff</strong>104-106 Albany Road, Cardiff, CF24 3RT<br> 02920 485 569</li>
        <li><strong>Crawley</strong>33 Queensway, Crawley, RH10 1EG<br>01295 522 189</li>
        <li><strong>Croydon</strong>89 London Road, Croydon, CR0 2RF (Next to LIDL)<br>+44(0) 20 8686 8846</li>
        <li><strong>Finsbury Park</strong>258 Seven Sisters Road, Finsbury Park, London, N4 2HY<br> 0207 281 5450</li>
        <li><strong>Forest Gate</strong>11 Woodgrange Road, Forest Gate, E7 8BA <br>020 8555 6508</li>  
        <li><strong>Fulham</strong>431 North End Road, Fulham Broadway, SW6 1NY<br>+44(0) 20 7381 4252</li>
        <li><strong>Gerrards Cross</strong>25 Packhorse Road, Gerrards Cross, SL9 7QA<br>017 53 887 271</li>
        <li><strong>Green Street Branch</strong>252 Green St, London E7 8LF<br>0203 649 5332</li>
        <li><strong>Hammersmith</strong>Istanbul Organic, Tariq Halal Express Counter, 120- 124 King Street, Hammersmith, London, W6 0QT<br>+44(0) 20 8741 6655</li>
        <li><strong>Holborn</strong>183 Drury Lane, London, WC2B 5QF<br>0207 430 9888</li>
        <li><strong>Hounslow</strong>9 High Street, Hounslow, TW3 1RH<br>+44(0) 20 3302 4330</li>
        <li><strong>Ilford</strong>48 Ilford Lane, Ilford, IG1 2JY<br>+44(0) 20 8911 8201</li>
        <li><strong>Leyton</strong>794 High Road, Leyton, E10 6AE<br>+44(0) 20 8539 6200</li> 
        <li><strong>Slough</strong>251 Farnham Road, Slough, SL2 1DE<br>+44(0) 17 5357 1609</li>
        <li><strong>South Harrow</strong>387 Northolt Road, Harrow, HA2 8JD<br>+44(0) 20 8423 4975</li>
        <li><strong>Southall Branch</strong>126 The broadway, Southall, UB1 1QF<br>0203 337 8794</li>
        <li><strong>Tariq Halal Chelmsford</strong>Unit 6 park central<br> Chelmsford, CM1 1GZ<br><span class="bg-black text-white px-2 py-1 mt-1 inline-block">Opening Soon</span></li>
        <li><strong>Tariq Halal Norbury</strong>1346 London Road, London SW16 4 DG<br>0777 111 1346</li>
        <li><strong>Tariq Halal - Romford</strong>17-19 Market Place, Romford, RM1 3AB<br>0170 836 8590</li>
        <li><strong>Southampton</strong>Unit 2 Ground Floor & Basement
124 Above Bar Street, Southampton, SO14 7DU<br><span class="bg-black text-white px-2 py-1 mt-1 inline-block">Opening Soon</span></li>
        
        <li><strong>St Johns Wood</strong>10 Lodge Road, London, NW8 7JA<br>07404 836 538</li>
        <li><strong>Stratford Shopping Centre</strong>Unit 47/48, The Mall Stratford, Shopping Centre, <br>E15 1XE<br>0204 506 5693</li>
        <li><strong>Streatham</strong>14 Leigham Parade, Streatham Hill, SW16 1DR<br>+44(0) 20 8664 7045</li>
        <li ><strong>Tariq Halal Green Street</strong>252 Green St, London E7 8LF<br>0203 649 5332</li>
        <li><strong>Tariq Supermarket</strong>14 -20 High Street, Wealdstone, HA3 7HA<br>0203 149 8382</li>
        <li><strong>Tariq Halal Bethnal Green</strong>465 Bethnal Green Road<br> London E2 9QW<br>0204 635 8780</li>
        <li><strong>SHIELDS GREEN<br>
(Tariq Halal Meats Glasgow)</strong>274 - 280 Shields Road<br>Glasgow, G41 1LA</li>
        <li><strong>Tariq Halal Purley</strong>909-911 Brighton Road, Purley, Surrey<br>CR8 2BP</li>

        <li><strong>Tariq Halal High Wycombe</strong>Al Rizq Supermarket<br>185 Dessborough Road, High Wycombe, HP11 2QN<br>01494 422 280</li>
        <li><strong>Tariq Halal Holborn</strong>183 Drury Lane, London, WC2B 5QF<br>0207 430 9888</li>
        <li ><strong>Tariq Halal Meats Reading</strong>477 Oxford Road, Reading, RG30 1HF <br>0118 956 0664</li>
        <li><strong>Tariq Halal Manchester - Longsight</strong>95 Hamilton Road - Longsight <br>Manchester M13 0AE<br>0161 566 5609</li>
        <li><strong>Tariq Halal - Old Kent Road</strong>282 - 286 Old Kent Rd, London SE1 5UE <br>0203 649 7157</li>
        <li><strong>Tooting</strong>147 Upper Tooting Road, Tooting, SW17 7TJ <br>+44(0) 20 8767 9113</li>
        <li><strong>Wembley (Outlet)</strong>259 Water Road, Wembley, HA0 1HX <br>+44(0) 20 8908 9440</li>

    </ul>
   

      </div>

      <div id="why" class="tab-content">
        <h2 class="text-xl md:text-2xl font-semibold mb-4">Why Become A Franchise</h2>
    <p class="mb-4"><strong>It’s simple. If you can agree to the statements below, then a franchise business is for you!</strong></p>
     <ul class="list-disc pl-6 space-y-2 mb-8">
      <li>Would you like to be your own boss?</li>
      <li>Would you like to own your own business?</li>
      <li>Would you like to join a successful business model?</li>
      <li>Would you like to be part of completely unique franchise?</li>
      <li>Would you like to be rewarded for your hard work?</li>

             
    </ul>
    <p class="mb-4"><strong>What can you expect as a Tariq Halal meat franchise?</strong></p>
   <ul class="list-disc pl-6 space-y-2 mb-8">
        <li>A supply of a wide variety of fresh, frozen, chilled, and marinated products, including chicken, lamb, turkey, beef and fish</li>
        <li>Our products and our business model are tried, tested and proven to succeed, reducing the business risk involved in opening a Halal franchise in UK</li>
        <li>Active support and expert advice at every stage of launching your business, from staff recruitment to product promotion and marketing</li>
        <li>Special training on food safety compliance, stock control, and equipment procurement, including package deals</li>
        <li>We offer ongoing, 'hands-on' assistance at every stage including help identifying the best premise lease deals, if needed</li>
        <li>We offer unlimited profit potential. This means, as a new Halal franchise in the UK, excellent profit margins and opportunity await you</li>

       
    </ul>
    <p class="mb-2">We are here to assist you in your achievement. Please enquire today.</p>
    <p>Contact us on 0208 998 4118 or email us at <a class="text-red underline" href="mailto:info@tariqhalalmeats.com">info@tariqhalalmeats.com</a></p>
      </div>

      <div id="look" class="tab-content">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6 items-start">
      
      <!-- LEFT CONTENT -->
      <div>
        <h2 class="text-xl md:text-2xl font-semibold mb-4">
          What We Look For
        </h2>

        <p class="text-sm md:text-base text-black leading-relaxed mb-4">
          To successfully expand, it is crucial that the right people are
          recruited to work with our team. We are looking for people with the
          right attitude – you must be prepared to follow an established
          business model and be flexible as changes arise. Previous business
          owners are ideal candidates, however we do welcome motivated
          individuals who possess an attitude to succeed.
        </p>

        <p class="text-sm md:text-base text-black">
          “Your business is our business. We can only succeed together”
        </p>
      </div>

      <!-- RIGHT IMAGE -->
      <div>
        <img
          src="/media/wysiwyg/wholesale-img.jpg"
          alt="What We Look For"
          class="w-full h-auto object-cover"
        />
      </div>

    </div>
      </div>

      <div id="apply" class="tab-content">
       <h2 class="text-xl md:text-2xl font-semibold mb-4">Apply Now</h2>
        <p class="mb-4">Applying to become a franchise is very simple.</p>
    <p class="mb-4">Please complete the following form and someone from our Franchise team will contact you directly.</p>
    <p class="mb-4"><strong>They can help with</strong></p>
    <ul class="list-disc pl-6 space-y-2 mb-8">
      <li>Finding site(s)</li>
      <li>Finance with the bank(s)</li>
      <li>Smooth construction of shop</li>
      <li>Access to the best suppliers for shop refits</li>
      <li>And much more….</li>

    </ul>

 <form class="form contact contact-us" method="post" action="<?= $this->getUrl('franchise')?>">
    <fieldset class="border-0">
  <div class="grid grid-cols-1 md:grid-cols-2 gap-6">

    <!-- Name -->
    <div class="relative">
      <label for="name" class="" >
        Name
      </label>
      <input
        type="text"
        id="name"
        name="name"
        required
        placeholder=" "
        class="w-full px-4 py-3 bg-white border border-gray-400"
      />
      
    </div>

    <!-- Email -->
    <div class="relative">
      <label for="email" class="" >
        Email
      </label>
      <input
        type="email"
        id="email"
        name="email"
        required
        placeholder=" "
        class="w-full px-4 py-3 bg-white border border-gray-400"
      />
      
    </div>

    <!-- Phone -->
    <div class="relative">
      <label for="telephone" class="" >
        Phone Number
      </label>
      <input
        type="text"
        id="telephone"
        name="telephone"
        required
        placeholder=" "
        class="w-full px-4 py-3 bg-white border border-gray-400"
      />
      
    </div>

    <!-- Business Phone -->
    <div class="relative">
      <label for="business_phone" class="" >
        Business Phone
      </label>
      <input
        type="text"
        id="Business-Phone"
        name="BusinessPhone"
        required
        placeholder=" "
        class="w-full px-4 py-3 bg-white border border-gray-400"
      />
     
    </div>

    <!-- Address -->
    <div class="relative">
      <label for="address" class="" >
        Address
      </label>
      <textarea
        id="Address"
        name="Address"
        rows="3"
        required
        placeholder=" "
        class="w-full px-4 py-3 bg-white border border-gray-400 resize-none"
      ></textarea>
      
    </div>

    <!-- Enquiry -->
    <div class="relative">
      <label for="enquiry" class="" >
        Enquiry
      </label>
      <textarea
        id="Enquiry" 
        name="Enquiry"
        rows="3"
        required
        placeholder=" "
        class="w-full px-4 py-3 bg-white border border-gray-400 resize-none"
      ></textarea>
      
    </div>

  </div>
</fieldset>
<div class="mt-8"> 
            <input type="submit" title="Submit" name="submit" class="action submit inline-block bg-[#3B7E48] hover:bg-[#E63833] group-hover:bg-[#E63833] text-white text-xs md:text-base  font-normal px-8 py-3 rounded-full transition duration-400 uppercase transition cursor-pointer" value="Submit">
     
    </div>
    </form>

    <?php 
if(isset($_POST['submit'])){
  //echo "string";exit();
}
?>


      </div>

      <div id="faq" class="tab-content">
        <h2 class="text-xl md:text-2xl font-semibold mb-4">FAQs</h2>

    <!-- FAQ Item -->
    <div class="border-b border-gray-300 py-4">
      <button
        class="faq-btn w-full flex justify-between items-center text-left font-semibold text-base cursor-pointer"
        onclick="toggleFaq(this)"
      >
        <span>Q. Why would I choose Tariq Halal Meats over another franchise</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Tariq Halal Meats represent an innovative breakthrough in the franchise meat market. We offer a unique business opportunity that can be operated in almost all communities across UK. The hours of operation are family orientated and the day-to-day operations are easy to learn and easy to teach. Our dedicated team provides a high level of support to each of our franchisees which reflects in the success of our brand to date.
      </div>
    </div>

     
    <div class="border-b border-gray-300 py-4">
      <button
        class="faq-btn w-full flex justify-between items-center text-left font-semibold text-base cursor-pointer"
        onclick="toggleFaq(this)"
      >
        <span>Q. How much does it cost to acquire a franchise?</span>
        <span class="text-xl">−</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Our dedicated franchise team will work with you to estimate costs.
      </div>
    </div>

    <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. Where are Tariq Halal Meats franchises available in UK?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Our prioritised location is London, however we are open to suggestions. Please call our team to see if your proposed site is viable. We will conduct a thorough analysis of each proposed site and review them independently. We are currently concentrating our development within London.
      </div>
    </div>

    <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. Do I need any previous retail or meat cutting experience?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        We do actively seek customers who have previous experience operating their own businesses, however we have a full training programme in place for new franchisees. We will train all approved candidates and offer ongoing training and learning opportunities to ensure that our franchisees are qualified to own and operate a Tariq Halal Meats Franchise location.
      </div>
    </div>

    <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. What qualities do Tariq Halal Meats look for in its franchisees?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        We look for driven, motivated and charismatic individuals who have people and/ or business management experience. Additionally, we look for financial acumen and the ability to learn as well as teach. Ultimately there needs to be a mutual fit between ourselves and the franchisee regarding corporate culture, brand, and our business ethics and morals.
      </div>
  </div>

  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. Is financing available from Tariq Halal Meats?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Tariq Halal Meats does not directly finance our franchisees however we have a qualified commercial manager that can help and assist with any relevant paperwork the bank requires. It is the franchisee candidate’s responsibility to secure financing, and they should undertake due diligence regarding any loans or loan approvals prior to becoming a franchisee.
      </div>
  </div>

  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. I don’t have enough money to open a Tariq Halal Meats Franchise but am very motivated. Can you assist me?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Tariq Halal Meats does not directly finance our franchisees, but there are occasions when we have current franchises that are looking to open or invest into additional locations. Providing that the franchisee candidate meets all our other criteria, we will do our best to assist them in partnering with an investor.
      </div>
  </div>


  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. How long does the Franchisee agreement last?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        The standard Tariq Halal Meats franchise agreement has a term of 5 years (bespoke agreements can be made depending on individuals)
      </div>
  </div>


  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. What form of training and guidance is provided by Tariq halal meats?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Tariq Halal Meats offers a comprehensive training programme over a period of 30 days which includes one-on-one instruction, study tools, in store training, manuals, testing materials and certification. After successful completion of the training programme, the Tariq Halal Meats store opening team then spends an additional 7 days at the franchisee’s new location. At minimum cost, we provide support and guidance until such time that the franchisee is capable to run their location independently.
      </div>
  </div>


  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. Where do I buy supplies?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        All the products are supplied by us. Tariq Halal Meats has partnered with the various abattoirs and supplier companies that will provide approved products to all Tariq Halal Meats Locations across the UK. Every store has access to semi-weekly deliveries, volume discounts, and cold chain management.
      </div>
  </div>


  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. Is there a risk to buying a Tariq Halal Meats Franchise?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        All business investments carry a level of risk. Tariq Halal Meats is no different. It is important to carry out due diligence, review all documents, and speak with all relevant individuals including your financial legal advisors prior to making an investment.
      </div>
  </div>

  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. How long has Tariq Halal Meats been in business?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Tariq Halal established themselves in 1965. After a successful wholesale business, Tariq Halal opened its first franchise location in 2010 and subsequently opened more soon after. The brand was started primarily as a fresh meat wholesale distributor and butcher shop, and has since expanded to sell fresh, frozen, and dry goods.
      </div>
  </div>

  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. Where is Tariq Halal Meats headquarters?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Tariq Halal Meats home office is located at 259 Water Road, Wembley, HA0 1HX
      </div>
  </div>

  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. How many Tariq Halal Meats stores are in operation, and where are they located?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Please visit our website for a complete and up to date list of our locations: www.tariqhalalmeats.com
      </div>
  </div>


  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. Who owns Tariq Halal Meats? Is it a public or private company?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Tariq Halal is a privately held company based in Wembley, London that specialises in franchise branding and growth
      </div>
  </div>


  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. What experience does the leadership team at Tariq halal meats have in growing and operating a franchise system?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Our leadership team has direct franchise experience with some of the latest corporations in the UK. They have held director level positions overseeing franchise development real estate, construction and purchasing, marketing, accounting, and operations departments. They hold advanced degrees and designations that are relevant to the business of operating a successful franchise system.
      </div>
  </div>


  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. Can I open more than one Tariq halal meats location?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Yes. Tariq Halal Meats’ business model has been designed to allow franchisees to own and operate multiple locations. Franchisees must first demonstrate operational and financial success prior to opening subsequent locations. In addition, Tariq Halal Meats may require specific multi-store training for franchisees seeking to open more than one location.
      </div>
  </div>


  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. What is your ongoing royalty fee?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        There is no royalty fee only a Franchise Fee (initial) of £40,000 + VAT
      </div>
  </div>


  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. What is the ongoing advertising fee?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
       The current advertising fee is monthly min £1000 + VAT depending on the size and location.
      </div>
  </div>

  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. What is the average size of a Tariq Halal Meats retail store?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Tariq Halal Meats locations are min 1600- 3000 sqft on average.
      </div>
  </div>


  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. What are Tariq Halal Meats’ typical hours of operations?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
       All Tariq Halal Meats locations operate daily from 8am-10pm
      </div>
  </div>

  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. How much money can I make with a Tariq Halal Meats Franchise?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Profitability depends on a number of factors. It is important to note that personal abilities, location and fiscal management amongst many other considerations will positively or negatively impact all business models and a Tariq Halal Meats Ltd Franchise is no different. In depth information regarding profit potential will be provided to you when you meet with Tariq Halal Meats Ltd.
      </div>
  </div>

  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. How long does it take to open a new Tariq halal meats franchise?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        It typically takes 6-12 months to open a new location
      </div>
  </div>

  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. Can I build my own store?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        No. Tariq Halal Meats provides a turn-key construction service through the provision of a project management team. We have found that our franchisee’s financial interests are better served learning the business of Tariq Halal Meats versus the business of construction.
      </div>
  </div>


  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. Can my friend or family do the electrical/plumbing/dry wall etc.?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        <strong>We are open to reviewing all trade references and passing them on to the local general contractor for consideration</strong> <br> Provided the trades are all able to meet budgets, timing and quality of workmanship we will do our best to ensure they are in the construction process.
      </div>
  </div>


  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. Are there sites available in my area?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Upon reviewing your application, Tariq Halal Meats will research available sites in your area and provide you with an answer.
      </div>
  </div>

  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. Does Tariq Halal Meats provide franchise support?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Yes. We provide valuable support in the following areas; training, site selection, construction, store design/equipment, store opening, operations and marketing.
      </div>
  </div>


  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. Is Tariq Halal an equal opportunity franchisor?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Yes, Tariq Halal Meats is committed to providing equal opportunities for all interested candidates across the UK. Our interests are tied to the success of our franchisees and we act accordingly.
      </div>
  </div>

  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. How does Tariq Halal Meats spend the advertising fees collected from each location?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
       Tariq Halal Meats spends 100% of the advertising fees collected in store marketing (print and video), as well as website and local marketing initiatives utilising modalities such as print and radio. Franchises are expected to allocate a percentage of sales for additional local store marketing that they personally direct.
      </div>
  </div>

  <div class="border-b border-gray-300 py-4">
      <button class="faq-btn w-full flex justify-between items-center text-left font-semibold cursor-pointer"
        onclick="toggleFaq(this)">
        <span>Q. Can I convert my current butcher shop into Tariq halal franchise?</span>
        <span class="text-xl">+</span>
      </button>
      <div class="faq-content hidden mt-3 text-sm text-black leading-relaxed">
        Yes, of course you can. We would be happy to work with you on managing the A-Z of the project and treat the new conversion as any Tariq Halal Franchise.
      </div>
  </div>

      </div>

      <div id="drive" class="tab-content">
        <h2 class="text-xl font-semibold">Drive-Thru</h2>
      </div>
    </div>

  </div>

  </div>
</section>

 


<script>
  const tabs = document.querySelectorAll(".tab-btn");
  const contents = document.querySelectorAll(".tab-content");

  tabs.forEach(tab => {
    tab.addEventListener("click", () => {
      tabs.forEach(t => t.classList.remove("active"));
      contents.forEach(c => c.classList.remove("active"));

      tab.classList.add("active");
      document.getElementById(tab.dataset.tab).classList.add("active");
    });
  });
</script>



<script>
  function toggleFaq(button) {
    const content = button.nextElementSibling;
    const icon = button.querySelector("span:last-child");

    content.classList.toggle("hidden");
    icon.textContent = content.classList.contains("hidden") ? "+" : "−";
  }
</script>
