<div class="trends-stories py-8 lg:py-28 px-4 max-w-7xl mx-auto">
   <div class="section-title text-center mb-12 scroll-item">
        <h2 class="text-2xl md:text-[38px] font-light text-black"><span class="font-bold">Trends</span> & Stories</h2>
        <p class="text-base md:text[17px] text-black my-4">
            Explore expert insights, tips, and stories
        </p>
        <span class="block w-10 h-0.5 bg-red-600 mx-auto mt-6"></span>
    </div>

    <!-- Recent Blog Posts -->
    <div class="grid gap-6 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-4 scroll-item">
    <?php
    $recentBlock = $this->getLayout()
        ->createBlock("Magefan\Blog\Block\Widget\Recent")
        ->setNoRepeatPostsEnable(1)
        ->setNumberOfPosts(4);

    $posts = $recentBlock->getPostCollection();
    ?>

    <?php if ($posts && $posts->getSize()): ?>
        <?php foreach ($posts as $post): ?>
            <div class="bg-white overflow-hidden hover:-translate-y-2 transition transform duration-300">
                <a href="<?= $post->getPostUrl() ?>" class="block overflow-hidden">
                    <?php if ($post->getFeaturedImage()): ?>
                        <img src="<?= $post->getFeaturedImage() ?>"
                             alt="<?= $block->escapeHtml($post->getTitle()) ?>"
                             class="w-full h-56 object-cover transform transition-transform duration-500 hover:scale-110">
                    <?php endif; ?>
                </a>
                <div class="py-6 px-0">
                    <p class="text-gray-400 text-xs uppercase font-semibold mb-2">
                        <?= date('F d, Y', strtotime($post->getPublishTime())) ?>
                    </p>
                    <a href="<?= $post->getPostUrl() ?>" class="block">
                        <h3 class="text-xl font-semibold text-black hover:text-red-600 mb-3 line-clamp-2">
                            <?= $block->escapeHtml($post->getTitle()) ?>
                        </h3>
                    </a>
                     <?php if ($post->getShortContent()){?>
                    <p class="text-base text-black text-[17px] line-clamp-3">
                     <?= $block->escapeHtml(strip_tags(
                              html_entity_decode($post->getShortContent(), ENT_QUOTES, 'UTF-8'))) ?>
                    </p>
                      <?php }?>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>

</div>