<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Advanced Search Hyva Compatibility M2 by Amasty
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductPrice;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Amasty\XsearchHyvaCompatibility\ViewModel\SearchPopup;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);
/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);
/** @var HeroiconsOutline $heroIcons */
$heroIcons = $viewModels->require(HeroiconsOutline::class);
/** @var ProductPrice $productPrice */
$productPrice = $viewModels->require(ProductPrice::class);
/** @var SearchPopup $popupViewModel */
$popupViewModel = $viewModels->require(SearchPopup::class);
// phpcs:disable Generic.Files.LineLength.TooLong
?>

<div
    class="z-10 item product product-item card card-interactive flex round-none
        shadow-none border-none flex-col mt-2 w-full md:w-auto md:max-w-md"
>
    <a
        :href="productItemUrl"
        class="photo product-item-photo mb-3 flex justify-center align-center"
        tabindex="-1"
    >
        <img
            class="hover:shadow-sm object-contain"
            :src="productItemSmallImageUrl"
            :alt="productItemSmallImageLabel"
            width="200"
        />
    </a>
    <div class="product-info flex flex-col grow text-center">
        <div class="mt-2 mb-1 items-center justify-center text-primary text-lg md:text-center">
            <a
                class="product-item-link action link"
                :href="productItemUrl"
            >
                <span
                    x-html="productItemName"
                    class="amsearch-product-name"
                ></span>
            </a>
            <template x-if="isShowProductItemSkuConfig">
                <div class="text-sm font-normal">
                    <span><?= $escaper->escapeHtml(__('SKU')) ?>:</span>
                    <span x-text="productItemSku"></span>
                </div>
            </template>
        </div>
        <template x-if="isProductItemReviewsBlockEnabledConfig">
            <?= /* @noEscape */ $block->fetchView(
                $block->getTemplateFile('Amasty_Xsearch::header-search/components/rating.phtml')
            ) ?>
        </template>
        <?= /** @noEscape */ $popupViewModel->fetchPriceView('header-search/components/price.phtml') ?>
        <div class="pt-3 flex flex-wrap items-center justify-start">
            <template x-if="isProductItemAddToCartBlockEnabledAndSalable">
                <button
                    type="button"
                    x-on:click.prevent="productItemAddToCartClickEvent"
                    class="action-addtocart w-auto btn btn-primary justify-center text-sm mb-3 md:mb-1"
                >
                    <?= $heroIcons->shoppingCartHtml("h-6 w-6 border-current inline", 25, 25) ?>
                    <span class="ml-2 inline"><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                </button>
            </template>
            <template x-if="!isProductItemAddToCartBlockEnabledAndSalable">
                <div class="action-addtocart w-auto justify-center text-sm mb-3 mr-3 md:mb-1 text-left">
                    <span class="inline-block w-3 h-3 bg-red-500 rounded-full flex-shrink-0"></span>
                    <span class="text-sm text-gray-700 text-left"><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                </div>
            </template>
            <?php if ($wishlistViewModel->isEnabled()): ?>
                <button
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')) ?>"
                    x-on:click.prevent="productItemAddToWishlistClickEvent"
                    class="action-wishlist rounded-full w-9 h-9 bg-gray-200 p-0 border-0
                        inline-flex shrink-0 items-center justify-center text-gray-500 hover:text-red-600 ml-1 mb-1"
                >
                    <?= $heroIcons->heartHtml("w-5 h-5", 25, 25) ?>
                </button>
            <?php endif ?>
            <?php if ($compareViewModel->showInProductList()): ?>
                <button
                    x-on:click.prevent="productItemAddToCompareClickEvent"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                    class="action-compare rounded-full w-9 h-9 bg-gray-200 p-0 border-0
                        inline-flex shrink-0 items-center justify-center text-gray-500 hover:text-yellow-500 ml-1 mb-1"
                >
                    <?= $heroIcons->scaleHtml("w-5 h-5") ?>
                </button>
            <?php endif ?>
        </div>
    </div>
</div>
