<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Advanced Search Hyva Compatibility M2 by Amasty
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductPrice;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Amasty\XsearchHyvaCompatibility\ViewModel\SearchPopup;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);
/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);
/** @var HeroiconsOutline $heroIcons */
$heroIcons = $viewModels->require(HeroiconsOutline::class);
/** @var ProductPrice $productPrice */
$productPrice = $viewModels->require(ProductPrice::class);
/** @var SearchPopup $popupViewModel */
$popupViewModel = $viewModels->require(SearchPopup::class);
// phpcs:disable Generic.Files.LineLength.TooLong
?>

<div class="item product product-item flex gap-x-3 lg:gap-x-4
     round-none shadow-none"
     :class="productItemViewClass">
    <a :href="productUrl"
       class="photo product-item-photo flex justify-center align-center"
       tabindex="-1"
        <?= $popupViewModel->isProductLabelEnabled() ? 'x-ref="amLabelParent"' : '' ?>
       :class="productSmallImageWrapperClass">
        <img class="hover:shadow-sm object-contain"
             :class="productSmallImageClass"
             :src="productSmallImageUrl"
             :alt="productSmallImageLabel"
            <?= $popupViewModel->isProductLabelEnabled() ? 'x-ref="amLabelImgParent"' : '' ?>
             width="60"/>

        <?php if ($popupViewModel->isProductLabelEnabled()): ?>
            <?= /* @noEscape */ $block->fetchView($block->getTemplateFile('Amasty_ProductLabelAdvancedSearch::components/product-wrapper.phtml')) ?>
        <?php endif ?>
    </a>
    <div class="product-info flex flex-col md:flex-row md:gap-x-2 grow">
        <div class="flex-1">
        <div class="items-center justify-center text-primary text-lg font-bold"
             :class="productInfoClass">
            <a class="product-item-link action link"
               :href="productUrl">
                <span x-html="productNameHtml" class="amsearch-product-name"></span>
            </a>
            <template x-if="isShowProductSkuConfig">
                <div class="text-sm font-normal">
                    <span><?= $escaper->escapeHtml(__('SKU')) ?>:</span>
                    <span x-html="productSku"></span>
                </div>
            </template>
        </div>

        <template x-if="isProductReviewsBlockEnabledConfig">
            <?= /* @noEscape */ $block->fetchView($block->getTemplateFile('Amasty_Xsearch::header-search/components/rating.phtml')) ?>
        </template>

        <div class=" items-center justify-center text-primary hidden"
             :class="productDescriptionClass"
             x-html="productDescriptionHtml"></div>
        <?= /** @noEscape */ $popupViewModel->fetchPriceView('header-search/components/price.phtml'); ?>

    </div>

        <div class="product-actions flex items-center gap-y-4 gap-x-2 mt-2"
             :class="productActionsWrapperClass">

            <template x-if="isProductAddToCartButtonEnabled">
                <button type="button"
                        class="action-addtocart flex items-center md:justify-center text-sm text-[#3B7E48] font-semibold bg-transparent uppercase"
                        x-on:click.prevent="productAddToCartButtonClickEvent"
                        :class="productAddToCartButtonClass">
                    <?= $heroIcons->plusHtml("h-3 w-3 border-current inline", 16, 16) ?>
                    <span class="ml-1 inline"><?= $escaper->escapeHtml(__('Add to Basket')) ?></span>
                </button>
            </template>

            <template x-if="productHidePriceNewAddToCart">
                <div x-html="productHidePriceNewAddToCart"></div>
            </template>

            <template x-if="isProductOutOfStock">
                <div class="action-addtocart w-auto justify-center text-sm text-left">
                    <span class="inline-block w-3 h-3 bg-red-500 rounded-full flex-shrink-0"></span>
                    <span class="text-sm text-gray-700 text-left"><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                </div>
            </template>
            <?php /*
            <?php if ($wishlistViewModel->isEnabled()): ?>
                <template x-if="isNotProductAmHidePriceWishlist">
                    <button aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')) ?>"
                            x-on:click.prevent="productAddToWishlistClickEvent"
                            class="action-wishlist rounded-full w-9 h-9 bg-gray-200 p-0 border-0 shrink-0
                            inline-flex items-center justify-center text-gray-500 hover:text-red-600 ml-1">
                        <?= $heroIcons->heartHtml("w-5 h-5", 25, 25) ?>
                    </button>
                </template>
            <?php endif ?>

            <?php if ($compareViewModel->showInProductList()): ?>
                <template x-if="isNotProductAmHidePriceCompare">
                    <button x-on:click.prevent="productAddToCompareClickEvent"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                            class="action-compare rounded-full w-9 h-9 bg-gray-200 p-0 border-0
                            inline-flex shrink-0 items-center justify-center text-gray-500 hover:text-yellow-500 ml-1">
                        <?= $heroIcons->scaleHtml("w-5 h-5") ?>
                    </button>
                </template>
            <?php endif ?>
            */?>
        </div>
    </div>
</div>
