<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Customer $customer */
$customer = $viewModels->require(Customer::class);
/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);
?>
 
 
        <div class="footer-left float-left md:w-[950px]">
        <!--Footer Menu-->
        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_menu')->toHtml(); ?>
        </div>
        <div class="footer-right float-right md:w-[275px]">
        <!--Newsletter Section-->
        <?php echo $this->getLayout()->createBlock(\Magento\Newsletter\Block\Subscribe::class)->setTemplate("Magento_Newsletter::subscribe.phtml")->toHtml(); ?>

        <!--Social Links Section-->
        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('social_links')->toHtml(); ?>
        </div>
 
 

 
 