<?php
/**
 * Copyright © 2017 ebizmarts. All rights reserved.
 * See LICENSE.txt for license details.
 */

/**
 * @var \Ebizmarts\SagePaySuite\Block\Adminhtml\Order\View\Info $block
 */

$payment = $block->getPayment();

?>

<div class="admin__page-section-item-title" style="margin-top: 20px;">
    <span class="title"><?= $block->escapeHtml(__('Opayo Information')); ?></span>

    <div class="actions">
        <a href="<?= $block->escapeHtmlAttr($block->getSyncFromApiUrl()); ?>">
            <?= $block->escapeHtml(__('Sync from API')); ?>
        </a></div>
</div>
<div class="admin__page-section-item-content">
    <div class="order-payment-additional order-payment-method-title">
        <table class="data-table admin__table-secondary">
            <tbody>
            <?php if ($payment->getLastTransId()):?>
                <tr>
                    <th><?= $block->escapeHtml(__('VPSTxId')); ?>:</th>
                    <td>
                        <?=
                        $block->escapeHtml($block->getSuiteHelper()->clearTransactionId($payment->getLastTransId()));
                        ?>
                    </td>
                </tr>
            <?php endif; ?>
            <?php if ($payment->getAdditionalInformation("vendorTxCode")): ?>
                <tr>
                    <th><?= $block->escapeHtml(__('VendorTxCode')); ?>:</th>
                    <td><?= $block->escapeHtml($payment->getAdditionalInformation("vendorTxCode")); ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($payment->getAdditionalInformation("mode")): ?>
                <tr>
                    <th><?= $block->escapeHtml(__('Mode')); ?>:</th>
                    <td>
                        <?=
                        $block->escapeHtml(strtoupper($block->escapeHtml($payment->getAdditionalInformation("mode"))));
                        ?>
                    </td>
                </tr>
            <?php endif; ?>
            <?php if ($payment->getAdditionalInformation("statusDetail")):
                $statusDetail = $payment->getAdditionalInformation("statusDetail");
                if (strrpos($payment->getAdditionalInformation("statusDetail"), " : ") !== false):
                    $statusDetail = explode(" : ", $statusDetail);
                    $statusDetail = $statusDetail[1];
                endif;
                ?>
                <tr>
                    <th><?= $block->escapeHtml(__('Status')); ?>:</th>
                    <td><?= $block->escapeHtml($statusDetail); ?></td>
                </tr>
            <?php endif; ?>
            <?php $statusCode = $payment->getAdditionalInformation("statusCode"); ?>
            <?php if ($block->isThreeDRedirect($statusCode)): ?>
                <tr>
                    <td colspan="2">
                        <div align="left" class="message message-info">
                            <p><?= $block->escapeHtml($block->getFirstParagraph()) ?></p>
                            <p><?= $block->escapeHtml($block->getSecondParagraph()) ?></p>
                            <p><?= $block->escapeHtml($block->getThirdParagraph()) ?></p>
                            <p><?= $block->escapeHtml($block->getForthParagraph()) ?></p>
                        </div>
                    </td>
                </tr>
            <?php endif; ?>
            <?php if ($payment->getAdditionalInformation("3DSecureStatus")): ?>
                <tr>
                    <th><?= $block->escapeHtml(__('3D Status')); ?>:</th>
                    <td><?= $block->escapeHtml($payment->getAdditionalInformation("3DSecureStatus")); ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($payment->getAdditionalInformation("AddressResult")): ?>
                <tr>
                    <th><?= $block->escapeHtml(__('Address Verification Result')); ?>:</th>
                    <td><?= $block->escapeHtml($payment->getAdditionalInformation("AddressResult")); ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($payment->getAdditionalInformation("PostCodeResult")): ?>
                <tr>
                    <th><?= $block->escapeHtml(__('Postcode Verification Result')); ?>:</th>
                    <td><?= $block->escapeHtml($payment->getAdditionalInformation("PostCodeResult")); ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($payment->getAdditionalInformation("AVSCV2")): ?>
                <tr>
                    <th><?= $block->escapeHtml(__('AVS/CV2 Applied')); ?>:</th>
                    <td><?= $block->escapeHtml($payment->getAdditionalInformation("AVSCV2")); ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($payment->getAdditionalInformation("CV2Result")): ?>
                <tr>
                    <th><?= $block->escapeHtml(__('CV2 Verification Result')); ?>:</th>
                    <td><?= $block->escapeHtml($payment->getAdditionalInformation("CV2Result")); ?></td>
                </tr>
            <?php endif; ?>
            <!-- Compatibility with orders placed with < v.1.4.1 -->
            <?php if ($payment->getAdditionalInformation("threeDStatus")): ?>
                <tr>
                    <th><?= $block->escapeHtml(__('3D Status')); ?>:</th>
                    <td><?= $block->escapeHtml($payment->getAdditionalInformation("threeDStatus")); ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($payment->getAdditionalInformation("avsCvcCheckAddress")): ?>
                <tr>
                    <th><?= $block->escapeHtml(__('Address Verification Result')); ?>:</th>
                    <td><?= $block->escapeHtml($payment->getAdditionalInformation("avsCvcCheckAddress")); ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($payment->getAdditionalInformation("avsCvcCheckPostalCode")): ?>
                <tr>
                    <th><?= $block->escapeHtml(__('Postcode Verification Result')); ?>:</th>
                    <td><?= $block->escapeHtml($payment->getAdditionalInformation("avsCvcCheckPostalCode")); ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($payment->getAdditionalInformation("avsCvcCheckSecurityCode")): ?>
                <tr>
                    <th><?= $block->escapeHtml(__('CV2 Verification Result')); ?>:</th>
                    <td><?= $block->escapeHtml($payment->getAdditionalInformation("avsCvcCheckSecurityCode")); ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($payment->getAdditionalInformation("avsCvcCheckStatus")): ?>
                <tr>
                    <th><?= $block->escapeHtml(__('AVS and CV2 Verification Result')); ?>:</th>
                    <td><?= $block->escapeHtml($payment->getAdditionalInformation("avsCvcCheckStatus")); ?></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<!--
**************** FRAUD INFORMATION SECTION *******************
-->

<div class="admin__page-section-item-title" style="margin-top: 20px;">
    <span class="title"><?= $block->escapeHtml(__('Fraud Information')); ?></span>
</div>
<div class="admin__page-section-item-content">
    <div class="order-payment-additional order-payment-method-title">
        <table class="data-table admin__table-secondary">
            <tbody>
            <?php if (!$block->isEnoughInformation(
                $payment->getAdditionalInformation("fraudscreenrecommendation")
            )
            ): ?>
                <tr>
                    <td colspan="2">
                            <?= $block->escapeHtml(__('Not enough information.')); ?>
                    </td>
                </tr>
            <?php else: ?>
                <?php if (!empty($payment->getAdditionalInformation("fraudprovidername"))): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Provider')); ?>:</th>
                        <td><?php if ($payment->getAdditionalInformation("fraudprovidername") == "ReD"):
                                $html = '<img style="height: 20px;" src="' .
                                $block->getViewFileUrl('Ebizmarts_SagePaySuite::images/red_logo.png') . '">';
                            else:
                                $html = '<span><img style="height: 20px;vertical-align: text-top;" src="' .
                                $block->getViewFileUrl('Ebizmarts_SagePaySuite::images/t3m_logo.png') . '"> T3M</span>';
                            endif;
                            /* @noEscape */ echo $html;
                            ?>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if (!empty($payment->getAdditionalInformation("fraudcodedetail"))): ?>
                    <?php $fraudDetails = $payment->getAdditionalInformation("fraudcodedetail")?>
                <?php endif; ?>
                <tr title="<?= $block->escapeHtmlAttr($fraudDetails) ?>">
                    <?php $infoImage = '<img style="height: 20px;vertical-align: text-top;" src="' .
                    $block->getViewFileUrl('Ebizmarts_SagePaySuite::images/info.png') . '">' ?>
                    <th><?= $block->escapeHtml(__('Fraud Recommendation')); ?>:</th>
                    <td >
                        <?php $html = $payment->getAdditionalInformation("fraudscreenrecommendation");
                        switch ($html):
                            case \Ebizmarts\SagePaySuite\Model\Config::REDSTATUS_CHALLENGE:
                            case \Ebizmarts\SagePaySuite\Model\Config::T3STATUS_HOLD:
                                $html = '<span style="color:orange;">' . $html . '</span>';
                                break;
                            case \Ebizmarts\SagePaySuite\Model\Config::REDSTATUS_DENY:
                            case \Ebizmarts\SagePaySuite\Model\Config::T3STATUS_REJECT:
                                $html = '<span style="color:red;">' . $html . '</span>';
                                break;
                        endswitch;
                        /* @noEscape */ echo $html;
                        ?>
                        <?= /* @noEscape */ " " . $infoImage?>
                    </td>
                </tr>
                <?php if (!empty($payment->getAdditionalInformation("fraudcode"))): ?>
                    <?php $fraudCode = $payment->getAdditionalInformation("fraudcode") ?>
                    <tr title="<?= $block->escapeHtmlAttr($fraudDetails) ?>">
                        <th><?= $block->escapeHtml(__('Fraud result')); ?>:</th>
                        <?php if ($fraudCode >= -1000 && $fraudCode <= 29): ?>
                            <td style="color:#228B22"><?php $html = $payment->getAdditionalInformation("fraudcode");
                                /* @noEscape */ echo $html;
                            ?>
                            </td>
                        <?php endif;?>
                        <?php if ($fraudCode >= 30 && $fraudCode <= 49): ?>
                            <td style="color:#FFA500"><?php $html = $payment->getAdditionalInformation("fraudcode");
                                /* @noEscape */ echo $html;
                            ?>
                            </td>
                        <?php endif;?>
                        <?php if ($fraudCode >= 50 && $fraudCode <= 1000): ?>
                            <td style="color:#FF0000"><?php $html = $payment->getAdditionalInformation("fraudcode");
                                /* @noEscape */ echo $html;
                            ?>
                            </td>
                        <?php endif;?>
                    </tr>
                <?php endif; ?>
                <?php if (!empty($payment->getAdditionalInformation("fraudrules"))): ?>
                    <tr>
                        <th><a href="" onclick="$('thirdman-breakdown').toggle();return false;">
                        <?= $block->escapeHtml(__('Show 3rd Man scores')); ?></a>:</th>
                    </tr>
                <?php endif; ?>
            <?php endif; ?>
            </tbody>
        </table>
        <?php if (!empty($payment->getAdditionalInformation("fraudrules"))): ?>
            <?php $rules = $payment->getAdditionalInformation("fraudrules") ?>
        <table id="thirdman-breakdown" class="data-table admin__table-secondary" style="display:none;">
            <tr>
                <th style="font-weight: bold"><?= $block->escapeHtml(__('DESCRIPTION')); ?>
                    <a href="https://www.opayo.co.uk/file/27641/download-document/fraud-prevention-guide.pdf"
                    target="_blank">
                            <?=
                            $block->escapeHtml(__('(More information)'));
                            ?>
                    </a>
                </th>
                <th style="font-weight: bold"><?= $block->escapeHtml(__('SCORE')); ?></th>
            </tr>
            <?php foreach ($rules as $rule): ?>
                <?php if (!empty($rule)): ?>
            <tr>
                <td style="text-align:left"><?= (string)$rule['description'] ?></td>
                <td style="text-align:left"><?= (string)$rule['score'] ?></td>
            </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        </table>
        <?php endif;?>
    </div>
</div>
