<section class="category-newsletter lg:max-w-[1100px] mx-auto bg-black text-white py-12 px-6 md:px-14 my-10 scroll-item">
  <div class="max-w-5xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
    <div class="text-center md:text-left">
      <h2 class="text-2xl md:text-[38px] font-light mb-4">Love a <strong class="font-bold">Good Deal?</strong></h2>
      <p class="text-white text-sm leading-[22px] md:text-[17px] md:leading-[26px]">
        Subscribe now and never miss out on our freshest<br class="hidden lg:block"> offers and updates.
      </p>
    </div>

    <div class="lg:w-[480px] inline-block">
        <?php
        /** @var \Magento\Newsletter\Block\Subscribe $block */
        echo $block->getLayout()
            ->createBlock(\Magento\Newsletter\Block\Subscribe::class)
            ->setTemplate('Magento_Newsletter::subscribe.phtml')
            ->toHtml();
        ?>
    </div>
</div>
</section>