<?php
declare(strict_types=1);

use Haartyhanks\FreeShippingProgressBar\ViewModel\Cart\ProgressBar;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var ProgressBar $viewModel */
$viewModel = $block->getData('viewModel');
$shippingLabel = 'FREE SHIPPING';

$progress = (float) $viewModel->getFreeShippingCompletionPercent();
$progressImage = $block->getViewFileUrl('images/truck.png');

?>
<?php if (!$viewModel->isCartEmpty()): ?>
<div class="freeship-progress w-full">
    <?php if (!$viewModel->isFreeShippingEligible()): ?>
        <p class="text-black text-sm font-normal md:text-[17px] mb-4">
            <?= /* @noEscape */ __(
                'Spend <span class="font-normal text-[#3B7E48]">%1 more to get free shipping.</span>',
                $viewModel->getFormattedPrice($viewModel->getFreeShippingDifference()),
                $shippingLabel
            ) ?>
        </p>

        <div class="space-y-4 relative discount-c-slider">
            
             <div class="flex justify-between mt-2 text-sm text-gray-600"> 
            <!-- Minimum price -->
            <span class="text-black-600 text-base sm:text-xl"><?= /* @noEscape */ $viewModel->getFormattedPrice(0, 0) ?></span>

            <!-- Maximum price (free shipping threshold) -->
            <span class="text-black-600 text-base sm:text-xl"><?= /* @noEscape */ $viewModel->getFormattedPrice($viewModel->getFreeShippingMinValue(), 0) ?></span>
        </div>

            <!-- Progress bar wrapper -->
            <div class="shiping-bar w-full relative">
                <!-- Filled bar -->
                <div class="shipping-bar-h transition-all duration-500 ease-in-out"
                     style="width: <?= $progress ?>%;">
                </div>

                <!-- Progress image marker -->
                <img src="<?= $progressImage ?>" 
                     alt="progress marker" 
                     class="absolute top-1/2 -translate-y-1/2"
                     style="left: <?= $progress ?>%; transform: translateX(-50%) translateY(-50%); height: 1.3rem; margin-top: -3px;">
            </div>
             
            
        </div>

    <?php else: ?>
        <div class="text-center p-3 sm:p-4 bg-green-50 rounded-lg">
            <p class="text-black text-sm font-normal md:text-[17px] mb-4">
                <?= /* @noEscape */ __(
                    'Your order is eligible for <span class="font-normal text-[#3B7E48]">%1!</span>',
                    $shippingLabel
                ) ?>
            </p>
        </div>
    <?php endif; ?>
</div>

<?php endif; ?>