<?php 

$custVipGroupId = $isLoggedIn = $loginUrl = '';
$isLoggedIn = $block->isLoggedIn();
if($isLoggedIn){

    $custVipGroupId       = $block->getVipGroupId();
    
    $rewardpointBlock     = $block->getLayout()->createBlock('Mageplaza\RewardPoints\Block\Account\Dashboard');
    $points               = explode(' ', $rewardpointBlock->getAvailableBalance(), 1);
      
    $rewardpointTierBlock = $block->getLayout()->createBlock('Mageplaza\RewardPointsUltimate\Block\Account\TierDashboard');
    $currentTier          = $rewardpointTierBlock->getCurrentTier();
    $upTier               = $rewardpointTierBlock->getUpTier($currentTier);
    $upPoint              = $rewardpointTierBlock->getUpPoint($upTier);
        
    $milestoneBlock       = $block->getLayout()->createBlock('Mageplaza\RewardPointsUltimate\Block\Milestone\Tier');
    $allTier              = $milestoneBlock->getAllTier();
    $milestonePoint       = $milestoneBlock->getMilestonePoint();
    $background           = $milestoneBlock->getTierBackGround();
    $rangeColor           = $milestoneBlock->getTierColor();
    $tierNumber           = count($allTier);
    $percentBar           = $tierNumber ? $milestoneBlock->getBarPercent($currentTier, $upTier) : 0;

}else{

    $loginUrl = $block->getLoginUrl();
}
?>
<!-- <div>Membership Page</div> -->

<div class="membership_page">
  <div class="vip_banner">
      <img src="<?php echo $this->getViewFileUrl('images/vip-membership-banner-new.jpg'); ?>" alt="">

  </div>
 
  <div class="membership_inner">
    <?php if (!$custVipGroupId) { ?>
    <div class="membership-top-content <?= ($isLoggedIn) ? 'member-login-content' : '' ?>">
        <h2>TARIQ HALAL</h2>
        <h1>VIP MEMBERSHIP</h1>
        <p>Earn points for your actions and turn them into awesome rewards!</p>
    </div>
    <?php } ?>
    <div class="login-membership"> 
      <div class="login-membership-details <?= ($isLoggedIn && $points[0] <= 500) ? 'login-membership-point' : ''?>" id="membershipLogin">           
        <?php if(!$custVipGroupId){ ?>
        <?php if(!$isLoggedIn){ ?>
        <div class="member-login">
          <p>ALREADY AN ACCOUNT HOLDER? LOGIN TO CHECK YOUR ELIGIBILITY</p>
        </div>
          <a class="login-btn" href="<?= $loginUrl ?>">Login</a>
        <?php } else { ?>
          <?php if($upPoint == 0){ ?>
              <a href="<?= $this->getUrl('membership/manage') ?>">Upgrade to VIP</a>            
          <?php } else { if($points[0] <= 500){ ?>
          <?= /** @noEscape */
              __('You’re nearly there! Only <strong>%1</strong> more Reward Points to earn and you will be eligible to unlock the privileges of our <strong>VIP</strong> Membership', $upPoint) ?>
          <?php }} ?>
          <div id="mp-reward-milestone-tier" class="<?= $block->escapeHtmlAttr($milestoneBlock->getTierClass($tierNumber)) ?>">
              <?php if ($tierNumber) : ?>
                <div class="mp-reward-progress">
                    <?php
                    foreach ($allTier as $tier) {
                        $locationClass = '';
                        $endClass      = '';
                        if ($tier->getId() === $currentTier->getId()) {
                            $locationClass = 'mp-tier-current';
                        } else {
                            if ($tier->getId() === $upTier->getId()) {
                                $locationClass = 'mp-tier-up';
                            }
                        }
                        if ($tier->getId() === $milestoneBlock->getEndTierId()) {
                            $endClass = 'mp-reward-step-end';
                        }
                        ?>
                        <div class="mp-reward-progress-step <?= /** @noEscape */
                        $locationClass ?> <?= /** @noEscape */
                        $endClass ?>">
                            <?php if ($milestoneBlock->checkIsPassStep($tier, $milestonePoint)) : ?>
                                <div class="mp-reward-step-range" title="<?= /** @noEscape */
                                $milestonePoint ?>"></div>
                            <?php endif; ?>
                            <div class="mp-reward-step-image
                            <?php if ($milestoneBlock->checkIsPassStep($tier, $milestonePoint)) {?>
                            mp-step-pass
                            <?php } ?> ">
                                <img src="<?= $block->escapeHtmlAttr($milestoneBlock->getImageUrl($tier)) ?>"
                                     alt="<?= /** @noEscape */ $tier->getName() ?>">
                            </div>
                            <div class="mp-reward-tier-info">
                                <div class="mp-reward-tier-name"><?= /** @noEscape */
                                    $tier->getName() ?></div>
                                <div class="mp-reward-tier-min-point"><?= /** @noEscape */
                                    $tier->getMinPoint() ?></div>
                                <?php if ($tier->getDescription()) : ?>
                                    <div class="mp-reward-tier-description"><?= /** @noEscape */
                                        $tier->getDescription() ?></div>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php } ?>
                </div>
                <script>
                    require(['jquery'], function ($) {
                        $('.mp-reward-step-image').mouseover(function () {
                            $(this).siblings('.mp-reward-tier-info').find('.mp-reward-tier-description').show();
                        }).mouseout(function () {
                            $(this).siblings('.mp-reward-tier-info').find('.mp-reward-tier-description').hide();
                        });
                    });
                </script>
              <?php endif; ?>
              <div class="box-current-tier">
                <?php if($points[0] <= 500){ ?>                    
                    <?= /** @noEscape */
                    __('Currently, you’re earning points as a Basic Account Holder.') ?> <br>                                  
                <!-- <a href="<?= $this->getUrl('/') ?>"> -->Earn 500 points to become a VIP Membership holder.<!-- </a> -->
                <?php }else{ ?>
                    <h3>Congratulations!</h3>
                    <?= /** @noEscape */
                    __('You have earned <strong>%1</strong> Reward Points and are now eligible for our <strong>%2</strong> Membership.', str_replace("point","",$points[0]), $currentTier->getName()) ?>
                <?php } ?>
              </div>
              <div class="vipmemberpage">
                  <?php if (!$custVipGroupId && $points[0] >= 500) { ?>
                  <?= /** @noEscape */
                  __('<span>Kindly <a href="%1">click here</a> to upgrade your Basic Account and join our membership program.</span>', $this->getUrl('membership/manage')) ?>
                  <?php } ?>
              </div>
          </div>
        <?php }} ?>        
      </div>
    </div>
    <?php if ($custVipGroupId && $isLoggedIn) { ?>
        <div class="member-sucess-page"><h3>CONGRATULATIONS!</h3> 
            <p>You are already a VIP member at Tariq Halal Meats</p>
            <p>Simply shop, share, or sign up today and earn more Reward Points</p>
        </div>
    <?php } ?>
    <div class="perk-details-section">
      <div class="perk-details">
        <h3>PERKS OF BECOMING A VIP MEMBER</h3>
        <div class="perl-list">
            <ul>
              <li>
                  <span>01</span>
                  <p>10% DISCOUNT ON YOUR FIRST ORDER AS A VIP MEMBER</p>
              </li>
              <li>   
                  <span>02</span>
                  <p>EACH ORDER YOU COMPLETE EARNS YOU POINTS</p> 
              </li>
              <li class="list-3">
                  <span>03</span>
                  <p>EARN 100 POINTS FOR EACH FRIEND YOU REFER</p>
              </li>
              <li class="list-4">
                  <span>04</span>
                  <p>FREE DELIVERY FOR CART VALUES OVER £75</p>
              </li>
            </ul>
        </div>
      </div>
    </div>
    <div class="membership-tab-section">
      <div class="membership-tab-content">
        <div class="membership-tab">
          <div class="tab-list">
            <button class="membership-tablinks earn-point" onclick="openCity(event, '1')" id="defaultOpen">Earn Points</button>
            <button class="membership-tablinks redeem-point" onclick="openCity(event, '2')">Redeem Points</button> 
          </div>
        </div>
        <div class="membership-tab-content-inner">
          <div id="1" class="membership-tabcontent">
          <h3>Ways to Earn Points</h3>
              <ol>
                  <li><span>01</span>
                      <p>By making a purchase</p></li>
                  <li><span>02</span>
                  <p>By referring a friend</p></li>
                  <li class="last"><span>03</span>
                  <p>By signing up for our newsletter</p></li>
              </ol>

          </div>
          <div id="2" class="membership-tabcontent redeem-points">
            <h3>Ways to Redeem Points</h3>
            <ol>
              <li><span>01</span><p>Use your points to save on your purchases</p></li>
              <li class="last"><span>02</span><p>Redeem your points with flexibility upon checkout</p></li>
            </ol>
          </div>
          <div class="membership-btn">
            <?php if(!$isLoggedIn){ ?>
                <a class="join-membership" href="#membershipLogin">JOIN OUR MEMBERSHIP</a>
            <?php } ?>
                <a class="start-earn" href="<?= $this->getUrl('/') ?>">START EARNING POINTS</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<?php if($isLoggedIn){ ?>
<style>
    #mp-reward-milestone-tier.mp-reward-vertical .mp-tier-current .mp-reward-step-range {
        height: <?= 100 * $percentBar ?>%;
    }

    #mp-reward-milestone-tier.mp-reward-horizontal .mp-tier-current .mp-reward-step-range {
        width: <?= 85 * $percentBar ?>%;
    }

    .mp-reward-vertical .mp-reward-step-range {
        background-color: <?= /** @noEscape */ $rangeColor ?>;
    }

    #mp-reward-milestone-tier .mp-reward-step-image.mp-step-pass {
        background-color: <?= /** @noEscape */ $rangeColor ?>;
    }

    .mp-reward-horizontal .mp-reward-step-range {
        background-color: <?= /** @noEscape */ $rangeColor ?>;
    }

    .mp-reward-vertical .mp-reward-progress-step:after {
        background-color: <?= /** @noEscape */ $background ?>;
    }

    .mp-reward-step-image {
        background-color: <?= /** @noEscape */ $background ?>;
    }

    .mp-reward-horizontal .mp-reward-progress-step:after {
        background-color: <?= /** @noEscape */ $background ?>;
    }

    .mp-tier {
        background-color: <?= /** @noEscape */ $rangeColor?>;
        border: 3px solid<?= /** @noEscape */ $rangeColor?>;
        box-shadow: inset 0 0 0 5px<?= /** @noEscape */ $background?>;
    }

    .progress {
        background-color: <?= /** @noEscape */ $background?>;
        border: 4px solid<?= /** @noEscape */ $rangeColor?>;
    }

    .bar {
        background-color: <?= /** @noEscape */ $rangeColor?>;
    }
</style>

<?php } ?>





<script>
function openCity(evt, cityName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("membership-tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("membership-tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " active";
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>

<style type="text/css">

/*------VIP Membership----*/

.cms-membership-page .page-main{
  max-width: 100%;
}

.cms-membership-page .page-main .membership_inner{
  max-width: 100%;
  margin: 0 auto;
}

.membership_page .vip_banner{
    width: 100%;
}

.membership_page .vip_banner img{
    width: 100%;
}


.membership-top-content{
    width: 100%;
      float: left;
      padding: 0;
      margin: 70px 0 0px 0;
}
.membership-top-content h2{
        width: 100%;
      float: left;
      padding: 0;
      margin: 0 0 0px 0;
      font-size: 38px;
      color: #000;
      font-weight: 400;
      line-height: 46px;
      font-family: 'Vidaloka', serif;
      text-align: center;
}
.membership-top-content h3{
        width: 100%;
      float: left;
      padding: 0;
      margin: 0 0 2px 0;
      font-size: 84px;
      color: #A36424;
      font-weight: 400;
      line-height: 86px;
      font-family: 'Vidaloka', serif;
      text-align: center;
}

.membership-top-content p{
    width: 100%;
      float: left;
      padding: 0;
      margin: 0 0 20px 0;
      font-size: 20px;
      color: #000;
      font-weight: 400;
      line-height: 26px;
      font-family: 'Lato', sans-serif;
      text-align: center;
}
.login-membership{
    width: 100%;
    float: left;
    text-align: center;
    margin-top: 9px;
}
.login-membership .login-membership-details p{
    width: auto;
      float: none;
      padding:20px 0 0 0;
      margin: 0 3px 5px 4px;
      font-size: 14px;
      color: #000;
      font-weight: 700;
      line-height: 26px;
      font-family: 'Lato', sans-serif;
      text-align: center;
      display: inline-block;
      text-transform: uppercase;
      letter-spacing: 0.45px;
}
.login-membership .login-membership-details a.login-btn{
    width: 253px;
      float: none;
      margin: 0 auto; 
      font-size: 19px;
      color: #000;
      font-weight: 700;
      line-height: 65px;
      font-family: 'Lato', sans-serif;
      text-align: center;
      display: inline-block;
      border: 0px solid #707070;
      text-transform: uppercase;
      margin-top: 6px;
      text-decoration: none;
      background-image: linear-gradient(to right, rgba(243,193,95,1), rgba(158,97,35,1));
      letter-spacing: 4px;
}
.login-membership .login-membership-details a.login-btn:hover{
    background: #e1ad53;
    color: #fff;
}


.perk-details-section{
    width: 100%;
    float: left;
    padding: 0 0 33px 0;
    margin:70px 0 0 0; 
    background:url('/pub/media/wysiwyg/vip-icon-new.png') left -193px top 12px no-repeat #FDEDEC;
}

.perk-details{
    max-width: 1130px;
    margin-left: auto;
    margin-right: auto;
    float: none;
    text-align: center;
    margin-top: 83px;
}
.perk-details h3{
    width: 100%;
      float: left;
      padding: 0;
      margin: 0 0 65px 0;
      font-size: 38px;
      color: #000;
      font-weight: 400;
      line-height: 46px;
      font-family: 'Vidaloka', serif;
      text-align: center;
}
.perl-list{
  width: 100%;
    float: left;
    text-align: center;  
}
.perl-list ul{
    padding: 0;
    margin: 0;
}
.perl-list ul li{
    list-style-type: none;
    background: #FDEDEC;
    font-size: 27px;
      color: #000;
      font-weight: 400;
      line-height: 34px;
      font-family: 'Vidaloka', serif;
      text-align: center;
      width: 42%;
      float: none;
      display: inline-block;
      padding: 32px 0;
      margin: 0 27px 70px 27px;
      box-shadow: 1px 2px 3px 1px rgb(0, 0, 0, 43%);
      text-transform: uppercase;
      position: relative;
      vertical-align: top;

}
.perl-list ul li p{
    height: 70px;
    margin-top: 15px;
    margin-bottom: 0;
    padding: 0 40px;
}

.perl-list ul li span{ 
      padding: 0;
      margin: 0 0 0px 0;
      font-size: 29px;
      color: #C0873B;
      font-weight: 400;
      line-height: 46px;
      font-family: 'Vidaloka', serif;
      text-align: center;
      position: absolute;
        top: -35px;
        border: 1px solid #E1A24D;
        width: 63px;
        line-height: 63px;
        line-height: 63px;
        border-radius: 50px;
        background: #fff;
        left: 43.3%;
        box-shadow: 2px 2px 2px 0px rgb(0, 0, 0, 24%);
}

.perl-list ul li:nth-child(odd) {background: #fff; border: 2px solid #E1A24D;}
.perl-list ul li:nth-child(even) {background-image: linear-gradient(to right, rgba(243,193,95,1), rgba(158,97,35,1)); color: #fff;  padding: 34px 0;}


.perl-list ul li.list-3{background-image: linear-gradient(to right, rgba(243,193,95,1), rgba(158,97,35,1)); border: 0; color: #fff;  padding: 34px 0;}
.perl-list ul li.list-4{background: #fff;  border: 2px solid #E1A24D; color: #000; padding: 32px 0;}
.membership-tab-content{
    width: 100%;
    float: left;
    background: #f2f2f2; 
    margin-top: 50px;
}
.membership-tab-content-inner{
    padding: 48px;
    display: inline-block;
}
.membership-tab{
    background: #fff;
    width: 100%;
    text-align: left;
}
.membership-tablinks{
    font-size: 16px;
      color: #000;
      font-weight: 700;
      line-height: 46px;
      font-family: 'Lato', sans-serif;
      text-align: center;
      padding: 80px 0 17px 0;
      border: 0 !important;
      width: 254px;
      box-shadow: none !important;
      background: #fff;
      border-radius: 0;
      text-transform: uppercase;
      letter-spacing: 1px;
}
.membership-tablinks.active{
    background-color: #f2f2f2 !important; 
}
.membership-tablinks:hover{
    background-color: #f2f2f2; 
}

.membership-tab-content-1{
    width: 48%;
    float: left;
    margin-right: 15px;
}
.membership-tab-content-1 h3,
.membership-tabcontent h3{
    width: 100%;
      float: left;
      padding: 0;
      margin: 0 0 15px 0;
      font-size: 24px;
      color: #000;
      font-weight: 400;
      line-height: 26px;
      font-family: 'Vidaloka', serif;
      text-align: left;
}

.membership-tab-content-1 p,
.membership-tabcontent p{
    width: 100%;
      float: left;
      padding: 0;
      margin: 0 0 20px 0;
      font-size: 20px;
      color: #000;
      font-weight: 400;
      line-height: 24px;
       font-family: 'Vidaloka', serif;
      text-align: left;
}
.membership-tab-content-1 ol,
.membership-tabcontent ol{
    padding: 0;
    margin: 0 0 0 17px;
}
.membership-tab-content-1 ol li,
.membership-tabcontent ol li{
    width: 100%;
      float: left;
      padding: 0;
      margin: 0 0 10px 0;
      font-size: 14px;
      color: #000;
      font-weight: 400;
      line-height: 20px;
      font-family: 'Lato', sans-serif;
      text-align: left;
}
.membership-tab-content .membership-btn,
.membership-tabcontent .membership-btn{
    width: 100%;
    float: left;
    margin-top: 25px;
}


.membership-btn a{
    width: 373px;
      float: left;
      padding: 0;
      margin: 0 32px 0px 0;
      font-size: 17px;
      color: #fff;
      font-weight: 700;
      line-height: 72px;
      font-family: 'Lato', sans-serif;
      text-align: center;
      background-image: linear-gradient(to right, rgba(243,193,95,1), rgba(158,97,35,1));
      letter-spacing: 2px;
}
.membership-btn a:hover{
    background: #e1ad53;
    text-decoration: none;
}

.membership-btn a.start-earn{
    background: #000;
}

.vipmemberpage,
.box-current-tier{
    font-size: 16px;
      color: #000;
      font-weight: 400;
      line-height: 30px;
      font-family: 'Lato', sans-serif;
}

.box-current-tier strong{
    font-weight: 700;
}
.vipmemberpage a{
    color: #cb9142;
}
.membership-link{
     background-image: linear-gradient(to right, rgba(245,193,97,1), rgba(168,105,40,1));
     padding-left: 20px !important;
     padding-right: 24px !important;
}
.membership-link a{
    background:url('/pub/media/wysiwyg/membership-icon.png') left center no-repeat;
    padding-left: 30px;
    font-size: 12px;
      color: #000;
      font-weight: 600 !important;
      line-height: 30px;
      font-family: 'Lato', sans-serif;
      letter-spacing: 0.30px;
}
.membership-details label{
    font-size: 17px;
      color: #000;
      font-weight: 400 !important;
      line-height: 30px;
      font-family: 'Lato', sans-serif; 
}
.membership-details label span{
    color: #EF0000;
}



@media (max-width: 480px) {
.membership-btn a{
    width: 100%;
    margin-right: 0;
    margin-bottom: 10px;
}

}

@media (max-width: 767px) {
.cms-membership-page .page-main .membership_inner{
    max-width: 100% !important;
}
.membership-tab-content-inner{
    padding: 20px;
}
.membership-tablinks{
    width: auto;
    font-size: 20px;
    padding: 0 15px;
}
.membership-tab-content-1 h3, .membership-tabcontent h3{
    font-size: 20px;
}
.membership-top-content h3{
    font-size: 50px;
    line-height: 60px;
}
.perk-details h3{
    font-size: 21px;
}
.perl-list ul li{
    width: 100%;
    margin-left: 0;
    margin-right: 0;
    line-height: 30px;
    font-size: 18px;
    padding: 20px 0;
    margin-bottom: 20px;
}
.perk-details{
    margin-top: 60px;
}

}


@media only screen and (min-width: 768px) and (max-width:977px) {
.membership-btn a{
    width: 260px;
}
.perl-list ul li{
    font-size: 20px;
    line-height: 30px;
}

}


.membership_inner .membership-top-content h1{
        width: 100%;
      float: left;
      padding: 0;
      margin: 0 0 2px 0;
      font-size: 84px;
      color: #A36424;
      font-weight: 400;
      line-height: 86px;
      font-family: 'Vidaloka', serif;
      text-align: center;
}

@media (max-width: 767px) {

    .membership-top-content{
        text-align: center;
    }
    .membership_inner .membership-top-content h1 {
        font-size: 38px;
        line-height: 50px;
    }
    .membership_inner .membership-top-content p {
        font-size: 18px !important;
        width: 96% !important;
        margin: 0 auto !important;
        float: none !important;
        display: inline-block;
    }
    .login-membership .login-membership-details p{
        margin-left: 10px;
        margin-right: 10px;
    }
    .mp-reward-tier-name{
        width: auto !important; 
    }
    .mp-reward-progress-step.mp-tier-up.mp-reward-step-end{
        width: 16%;
    }
    .mp-reward-progress-step.mp-tier-current{
        width: 75% !important;
    }
    .perl-list ul{
        width: 90%;
        margin: 0 auto;
    }
    .perl-list ul li p{
        padding: 0 30px !important;
    }
    .membership-tab-content-1 ol, .membership-tabcontent ol{
        margin-left: 0 !important;
    }
}

.mp-reward-progress{
        display: flex;
        height: 100px;
        margin-top: 40px;
        justify-content: center;
}
.mp-reward-step-image img{
    margin: 18px 0 !important;
    width: auto !important;
    height: auto !important;
}

.mp-reward-progress-step.mp-tier-current{
    width: 25%;
    position: relative;
}
.mp-reward-step-image{       
    width: 60px;
        height: 60px;
        border-radius: 50%;
        text-align: center;
        z-index: 2;
        position: absolute;
        overflow: hidden;
        box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
        align-content: center;
        justify-content: center;
        display: flex;
        background-color: #f3cfcd;
}
.mp-reward-tier-info{
    position: relative;
}
.mp-reward-tier-name{
        position: absolute;
        top: -35px;
        left: 13px;
        width: 200px;
        text-align: justify;
}
.mp-reward-tier-min-point{
        position: absolute;
        top: 65px;
        left: 5px;
        width: 50px;
        text-align: center;
}

.mp-reward-progress-step.mp-tier-current:after {
    height: 20px;
    top: 20px;
    background-color: #f3cfcd;
        content: '';
        position: absolute;
        width: 96%;
        height: 20px;
        margin: auto 5px auto 0;
        top: 20px;
        left: 15px;
        box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
}

.member-login{
            position: relative;
        }
        .membership-tab-section{
            max-width: 1130px;
            margin: 0 auto;
        }

        .membership-tablinks.earn-point{
            background:url('/pub/media/wysiwyg/earn-point.png') center 32px no-repeat;
        }
        .membership-tablinks.redeem-point{
            background:url('/pub/media/wysiwyg/redeem-point.png') center 32px no-repeat;
        }
        .membership-tab-content-inner .membership-tabcontent h3{
            font-size: 34px;
            color: #000;
            font-weight: 400;
            line-height: 46px;
            font-family: 'Vidaloka', serif;
            text-align: left;
            text-transform: uppercase;
            padding-bottom: 17px;
        }
        .membership-tab-content-inner{
            width: 100%;
        }
        .membership-tab-content-inner .membership-tabcontent ol{
            margin-left: 0;
        }
        .membership-tab-content-inner .membership-tabcontent ol li{
            width: 300px;
            margin-right: 0px;
            padding-right: 50px;
            font-size: 16px;
            color: #222;
            list-style-type: none; 
            /*background:url('/pub/media/wysiwyg/list-arrow.png') right center no-repeat;*/
        }
        .membership-tab-content-inner .membership-tabcontent ol li:last-child{
            background: none;
            width: 338px;
            padding-right: 0;
        }
        .membership-tab-content-inner .membership-tabcontent ol li span{
            width: 100%;
            float: left;
            text-align: center;
            font-size: 29px;
              color: #C0873B;
              font-weight: 400;
              line-height: 40px;
               font-family: 'Vidaloka', serif; 
        }
        .membership-tab-content-inner .membership-tabcontent ol li p{
            font-size: 16px;
            color: #000;
            font-weight: 400;
            line-height: 20px;
            font-family: 'Lato', sans-serif;
            text-align: center;
            width: 100%;
            padding: 0 32px;
        }

        .membership-tab-content-inner .membership-tabcontent ol li:after{
            content: 'Or';
            float: right;
            top: -45px;
            position: relative;
            left: 40px;
            font-size: 25px;
            color: #C0873B;
            font-weight: 400;
            line-height: 30px;
            font-family: 'Vidaloka', serif;
        }
        .membership-tab-content-inner .membership-tabcontent.redeem-points ol li{
           width: 450px;
        }
        .membership-tab-content-inner .membership-tabcontent.redeem-points ol li:after{
           left: 15px;
        }
        .membership-tab-content-inner .membership-tabcontent ol li.last:after{
            display: none;
        }

        @media only screen and (min-width: 768px) and (max-width:977px) {
            .membership-tab-content-inner .membership-tabcontent ol li:after{
            display: none;
          }
            .membership-tab-content-inner {
                width: 87%;
            }
            .membership-tab-content-inner .membership-tabcontent ol li{
                width: 100% !important;
                background: none;
            }
            .membership-tab-content-inner .membership-tabcontent ol li p{
                text-align: left;
                width: auto;
                padding: 0 0px;
                float: left;
                line-height: 34px;
                padding-bottom: 0;
                margin-bottom: 0;
            }
            .membership-tab-content-inner .membership-tabcontent ol li span{
                text-align: left;
                width: auto;
                float: left;
                margin-right: 10px;
            }
            .login-membership-details .member-login:before{
                left: 43.5%;
            }
            .login-membership .login-membership-details{
                padding: 0 !important;
            }
            .perk-details-section .perl-list ul li{
                line-height: 26px !important;
            }
            .perk-details-section .perl-list ul li span{
                left: 40%;
            }
        }

        @media only screen and (min-width: 978px) and (max-width:1024px) {

            .header.panel > .header.links > li.membership-link {
                display: none;
            }
            .membership-tab-content-inner .membership-tabcontent ol li,
            .membership-tab-content-inner .membership-tabcontent ol li:last-child{
                width: 270px;
            }
            .perk-details-section .perl-list ul li span{
                left: 42.8%;
            }
            .login-membership-details .member-login:before{
                left: 45.2%;
            }
            .login-membership .login-membership-details{
                padding: 0 !important;
            }
        }

        @media (max-width: 767px) {

            .member-sucess-page h3{
                font-size: 32px !important;
            }
            .member-sucess-page p{
                width: 92% !important;
                float: none !important;
                padding: 0 15px;
                margin: 15px auto;
            }
            .membership-tab-content-inner .membership-tabcontent ol li:after{
            display: none;
          }
            .membership-tab-content-inner .membership-tabcontent ol li{
                width: 100% !important;
                background: none;
                padding-right: 0;
            }
            .membership-tab-content-inner .membership-tabcontent ol li p{
                text-align: left;
                width: 80%;
                padding: 0 0px;
                float: left;
                line-height: 24px;
                padding-bottom: 0;
                margin-bottom: 0;
                margin-top: 8px;
            }
            .membership-tab-content-inner .membership-tabcontent ol li span{
                text-align: left;
                width: auto;
                float: left;
                margin-right: 10px;
            }
            .membership_inner .membership-top-content h2{
                font-size: 32px;
                line-height: 36px;
            }
            .membership_inner .membership-top-content h3{
                font-size: 38px;
                line-height: 50px;
            }
            .login-membership-details .member-login:before{
                display: none;
            }
            .membership-top-content p{
                background:url('/pub/media/wysiwyg/sep-line.png') bottom center no-repeat;
                padding-bottom: 20px !important;
                margin-bottom: 0 !important;
            }
            .login-membership .login-membership-details p{
                padding-top: 10px !important;
            }
            .perk-details-section{
                margin-top: 50px !important;
            }
            .cms-membership-page .page-main{
                padding-left: 0 !important;
                padding-right: 0 !important;
            }
            .membership-tab-content-inner{
                width: auto !important;
            }
            .perl-list ul li{
                width: 90% !important;
                margin-bottom: 50px !important;
            }
            .membership-top-content p{
                font-size: 18px !important;
            }
            .membership-tab-content-inner .membership-tabcontent h3{
                font-size: 25px !important;
                line-height: 36px !important;
                padding-bottom: 0 !important;
            }
            .membership-tablinks.earn-point,
            .membership-tablinks.redeem-point{
                background-position: center 15px !important;
                padding: 65px 15px 20px 15px !important;
                font-size: 16px !important;
            }
            .membership-top-content.member-login-content p{
                background: none !important;
            }
            .login-membership .login-membership-point{
                padding-top: 40px !important;
                margin-top: 10px !important;
            }
        }

        .membership-top-content.member-login-content h3{
            color: #000;
        }


</style>