<div class="vip-competition">
<div class="vip_cop-banner desktop">
       <img src="<?php echo $this->getViewFileUrl('images/vip-main-banner.jpg'); ?>" alt="" />

</div>
<div class="vip_cop-banner mobile">
       <!-- <img src="<?php //echo $this->getViewFileUrl('images/vip-main-banner-mobile.jpg'); ?>" alt="" /> -->

</div>

<div class="vip-competition-content">
	<div class="container">
		<h2>Starts from 10th January 2022</h2>
		<ul>
			<li class="first-place"><h3>1st <span>PLACE</span></h3>
				<p>Instant VIP Membership to Tariq Halal's New Rewards Club with 2000 points.</p> 
				<p>An exclusive online VIP shopping experience worth £200</p>
			</li>
			<li class="second-place"><h3>2nd <span>PLACE</span></h3>
				<p>Instant VIP Membership to Tariq Halal's New Rewards Club with 1000 points.</p>
				<p>An exclusive online VIP shopping experience worth £150</p>
			</li>
			<li class="third-place"><h3>3rd <span>PLACE</span></h3>
				<p>Instant VIP Membership to Tariq Halal's New Rewards Club with 750 points.</p> 
				<p>An exclusive online VIP shopping experience worth £75</p>
			</li>

		</ul>
		<div class="register-button"><a href="https://www.tariqhalalmeats.com/customer/account/login/">REGISTER WITH US</a></div>
	</div>
</div>

<div class="vip-competition-content-2">
		<div class="container">
			<h2>How to Enter THE COMPETITION</h2>

			<div class="vip-left-content">
				<h4>Step 1: recipe submission</h4>
				<p>Simply DM us 3-4 of your best portrait orientated images along with the name of the recipe you're sharing. Our team will select and post the best 3. Please allow up to 48 hours to see your post online.</p>
				<p>Along with your recipe submission, you will need to submit to us the handles of 5 friends who will be tagged with your recipe when we share your post.</p>
				<p>To qualify for winning placement, once your submission has been shared to our infeed, you must repost it as a story on your own page tagging the 5 friends who were included in your initial submission.</p>
				<h4 class="step-prize">Step 2: prize</h4>
				<p>1st, 2nd, and 3rd place will be awarded, however in order to be eligible for the first place prize, your post must receive a minimum of 500 likes.</p>
				<h4 class="step-prize">Step 3: winners</h4>
				<p>Entry submission closes on 31st Jan. From that date until 7th Feb, entrants will be granted a period of time to accumulate as many likes as possible with the posts receiving the highest number of likes declared the winners. Winners of the competition will be announced on 10th Feb.</p>
			</div>

			<div class="vip-right-img">

			<!-- <img src="<?php //echo $this->getViewFileUrl('images/vip-img-2.jpg'); ?>" alt="" /> --></div>
		</div>
</div>


<div class="vip-competition-content-2 white-bg">
		<div class="container">
			<h2>WHO is Eligible</h2>
			<div class="vip-left-img">

			<!-- <img src="<?php //echo $this->getViewFileUrl('images/vip-img-2.jpg'); ?>" alt="" /> --></div>

			<div class="vip-right-content">
				<ul>
					<li>Competition is open to UK Residents Only</li>
					<li>Participants may only enter once</li>
					<li>If we are unable to deliver a prize to your location in the UK, collection can be arranged from a nominated store</li>
					<li>VIP Reward Points can only be awarded to registered users of <a href="https://www.tariqhalalmeats.com/">www.tariqhalalmeats.com</a></li>
					<li>Submissions must be received through Instagram.</li>

				</ul>
				<div class="register-button"><a href="https://www.tariqhalalmeats.com/customer/account/login/">REGISTER WITH US</a></div>
			</div>

			
		</div>
</div>


</div>

<style type="text/css">
	.vip_cop-banner{
		width: 100%;
		float: left;
		/*height: 570px;
		background: url('/pub/media/wysiwyg/vip-main-banner.jpg') center no-repeat;*/
	}
	.cms-vip-recipe-competition.page-layout-1column .page-main{
		max-width: 100%;
		padding: 0 !important;
	}
	.cms-vip-recipe-competition.page-layout-1column .breadcrumbs{
		display: none;
	}
	.vip-competition-content .container,
	.vip-competition-content-2 .container{
		max-width: 1100px;
		margin: 0 auto;
	}

	.vip-competition-content{
		padding: 70px 0 100px 0;
		width: 100%;
		float: left;
	}
	.vip-competition-content h2,
	.vip-competition-content-2 h2{
		width: 100%;
	    float: left;
	    padding: 0px 0 0 0;
	    margin: 0 0 0px 0;
	    font-size: 50px;
	      color: #000;
	      font-weight: 400;
	      line-height: 46px;
	      font-family: 'Vidaloka', serif;
	      text-align: center;
	      letter-spacing: 1px;
	      text-transform: uppercase;
	}
	.vip-competition-content ul{
		width: 100%;
		float: left;
		padding: 0;
		margin:100px 0 0 0;
		list-style-type: none;
	}
	.vip-competition-content ul li{
		width: 354px;
		float: left;
		padding:35px 0 30px 0;
		margin: 0 6px;
		list-style-type: none;
		background: #f9f9f9;
		text-align: center;
	}
	.vip-competition-content ul li.price-middle{
		background: #fdedec;
	}
	.vip-competition-content ul li h3{
		width: 127px;
		text-align: center;
		font-size: 49px;
	      color:#BF7A01;
	      font-weight: 400;
	      line-height: 28px;
	      font-family: 'Vidaloka', serif;
	      text-align: center;
	      text-transform: uppercase;
	      padding:15px 0 0 0;
	      margin: -95px auto 17px auto;
	      height: 112px;
	      border-radius: 100px;
	      display: flex;
	    flex-direction: column;
	    align-items: center;
	    justify-content: center;
	}
	.vip-competition-content ul li h3 span{
		font-size: 16px;
		font-weight: 700;
		font-family: 'Lato', sans-serif;
		letter-spacing: 3px;
		color: #7C7C7C;
	}
	.vip-competition-content ul li p{
	 
		text-align: center;
		font-size:15px;
	      color: #000;
	      font-weight: 400;
	      line-height: 20px;
	      font-family: 'Lato', sans-serif;
	      text-align: center;
	      padding: 0 20px;
	      margin: 0 0 10px 0;
	}
	.vip-competition-content sup {
	    top: -10px;
	    font-size: 16px;
	}

	.vip-competition-content-2{
		width: 100%;
		float: left;
		background: #fdedec;
		padding: 70px 0;
	}

	.vip-competition-content-2 .vip-left-content{
		width: 485px;
		float: left;
	}
	.vip-competition-content-2 .vip-right-img{
		width: auto;
		float: right;
	}

	.vip-competition-content-2 h2{
		margin-bottom: 70px;
	}
	.vip-competition-content-2.white-bg{
		background: #fff;
	}
	.vip-competition-content-2.white-bg{
		margin-bottom: 0px;
		margin-top: 10px;
	}

	.vip-competition-content-2 .vip-left-img{
		width: auto;
		float: left;
		margin-right: 55px;

	}
	.vip-competition-content-2 .vip-right-content{
		width: 450px;
		float: left;

	}

	.vip-competition-content-2 .vip-right-content ul{
		padding: 0;
		margin: 0 0 0 15px;
	}
	.vip-competition-content-2 .vip-right-content ul li{
		font-size:16px;
	      color: #000;
	      font-weight: 400;
	      line-height: 25px;
	      font-family: 'Lato', sans-serif;
	      text-align: left;
	      margin-bottom: 22px;
	}
	.vip-competition-content-2 .vip-right-content ul li a{
		color: #000;
		text-decoration: none;
	}
	.vip-competition-content-2 .vip-right-content ul li a:hover{
		text-decoration: underline;
	}
	.vip-competition-content-2 h4{
	 
		text-align: center;
		font-size:18px;
	      color: #000;
	      font-weight: 700;
	      line-height: 20px;
	      font-family: 'Lato', sans-serif;
	      text-align: left;
	      padding: 0 0px;
	      margin: 0 0 15px 0;
	      text-transform: uppercase;
	}
	.vip-competition-content-2 p{
	 
		text-align: center;
		font-size:13px;
	      color: #000;
	      font-weight: 400;
	      line-height: 20px;
	      font-family: 'Lato', sans-serif;
	      text-align: left;
	      padding: 0 0px;
	      margin: 0 0 10px 0;
	}

	.vip-competition-content-2 .register-button a{
		width: 345px;
	    float: none;
	    margin: 0 auto;
	    font-size: 17px;
	    color: #000;
	    font-weight: 700;
	    line-height: 72px;
	    font-family: 'Lato', sans-serif;
	    text-align: center;
	    display: inline-block;
	    border: 0px solid #707070;
	    text-transform: uppercase;
	    margin-top: 15px;
	    text-decoration: none;
	    background-image: linear-gradient(to right, rgba(243,193,95,1), rgba(158,97,35,1));
	    letter-spacing: 4px;
	}
	.vip-competition-content-2 .register-button a:hover {
	    background: #e1ad53;
	    color: #fff;
	}

	.vip-left-img {
		height: 386px;
		background: url('/pub/media/wysiwyg/vip-img-3.jpg') center no-repeat;
		width: 550px !important;
	}

	.vip-right-img{
		height: 465px;
		background: url('/pub/media/wysiwyg/vip-img-2.jpg') center no-repeat;
		width: 550px !important;
	}


@media screen and (max-width: 767px) {
	.cms-vip-recipe-competition .vip-competition-content .container, .vip-competition-content-2 .container{
		max-width: 100% !important;
	}
	.cms-vip-recipe-competition .vip-competition-content ul li,
	.cms-vip-recipe-competition .vip-competition-content-2 .vip-left-content,
	.cms-vip-recipe-competition .vip-left-img, 
	.cms-vip-recipe-competition .vip-right-img,
	.cms-vip-recipe-competition .vip-competition-content-2 .vip-right-content{
		width: 100% !important;
	}

	.vip-competition-content{
		padding: 40px 0 50px 0 !important;
	}
	.vip-competition-content h2, .vip-competition-content-2 h2{
		font-size: 33px !important;
		line-height: 40px !important;
	}
	.vip-competition-content .register-button{
		margin-top: 0 !important;
	}
	.vip-competition-content ul li h3{
		margin-top: -77px !important;
	}
	.vip-competition-content ul{
		margin-top: 100px !important;
	}
	.vip-competition-content ul li{
		padding: 20px 0 !important;
		margin-bottom: 80px;
		margin-right: 0 !important;
		margin-left: 0 !important;
	}
	.vip-competition-content-2{
		padding: 35px 0 !important;
	}
	.vip-competition .vip-competition-content-2 .vip-left-content,
	.vip-competition .vip-competition-content-2 .vip-right-content{
		width: 90% !important;
		margin-left: 15px;
	}
	.vip-competition-content-2 p{
		font-size: 15px !important;
		line-height: 22px !important;
	}
	.vip-competition-content-2 h2{
		margin-bottom: 25px !important;
	}


	.vip-competition-content-2 .vip-right-content ul li{
		font-size: 15px !important;
		line-height: 22px !important;
		margin-bottom: 10px !important;
	}
	.vip-competition-content-2 .register-button a{
		width: 100% !important;
		line-height: 60px !important;
	}
	.vip-competition .vip-competition-content-2 .vip-right-content{
		margin-top: 0px;
	}
	.vip-competition .vip-competition-content-2 .vip-right-content ul{
		margin-bottom: 35px !important;
	}
	.vip-competition .vip-left-img, .vip-competition .vip-right-img{
		display: none;
	}

}

@media only screen and (min-width:768px) and (max-width:977px){


.vip-competition-content h2, .vip-competition-content-2 h2{
	font-size: 35px !important;
}
.vip-competition-content ul li{
	width: 218px !important;
}
.vip-competition-content .container, .vip-competition-content-2 .container{
	max-width: 90% !important;
}
.vip-competition-content-2 .vip-right-img {
    width: 330px !important;
    float: right;
}
.vip-competition-content-2 .vip-left-content{
	width: 330px !important;
}
.vip-competition-content-2 .vip-left-img{
	 width: 330px !important;
	margin-right: 0 !important;
}
.vip-competition-content-2 .vip-right-content {
    width: 330px !important;
    float: right !important;
}

.vip-competition-content-2 p{
	font-size: 15px !important;
	line-height: 20px !important;
	margin-bottom: 30px !important;
}

.vip-competition-content-2 .vip-right-content ul li{
	font-size: 15px !important;
	line-height: 22px !important;
	margin-bottom: 22px !important;
}
.vip-competition-content-2 .register-button a{
	width: 100% !important;
}

}

@media only screen and (min-width:978px) and (max-width:1024px){

.vip-competition-content ul li{
	width: 295px !important;
}
.vip-competition-content .container, .vip-competition-content-2 .container{
	max-width: 90% !important;
}
.vip-competition-content-2 .vip-right-img {
    width: 480px !important;
    float: right;
}
.vip-competition-content-2 .vip-left-content{
	width: 420px !important;
}
.vip-competition-content-2 .vip-left-img{
	 width: 480px !important;
	margin-right: 0 !important;
}
.vip-competition-content-2 .vip-right-content {
    width: 400px !important;
    float: right !important;
}

}

.vip-competition-content ul li.first-place{
	background: #d89f3c;
}
.vip-competition-content ul li.second-place{
	background: #cecdcd;
}
.vip-competition-content ul li.third-place{
	background: #b16f39;
}


.vip-competition-content ul li.first-place h3{
	background: #fff5e4;
}
.vip-competition-content ul li.second-place h3{
	background: #f3f3f3;
	color: #000;
}
.vip-competition-content ul li.third-place h3{
	background: #feefe2;
}

.vip-competition-content .register-button{
	width: 100%;
	text-align: center;
	float: left;
	margin-top: 47px;
}

.vip-competition-content .register-button a{
	    width: 355px;
	    float: none;
	    margin: 0 auto;
	    font-size: 17px;
	    color: #fff;
	    font-weight: 700;
	    line-height: 72px;
	    font-family: 'Lato', sans-serif;
	    text-align: center;
	    display: inline-block;
	    border: 0px solid #707070;
	    text-transform: uppercase; 
	    text-decoration: none;
	    background: #000;
	    letter-spacing: 3px;
	}
.vip-competition-content .register-button a:hover {
	    background: #e1ad53;
	    color: #fff;
	}

.vip-competition-content-2 .vip-left-content .step-prize{
	margin-top: 30px;
}


.vip-competition .vip_cop-banner.mobile{
	display: none;
}

@media screen and (max-width: 480px) {
.vip-competition .vip_cop-banner.mobile{
	display: block !important;
	height: 411px;
	background: url('/pub/media/wysiwyg/vip-main-banner-mobile.jpg') center no-repeat;
	width: 100%;
    background-size: 100%;
}
.vip-competition .vip_cop-banner.desktop{
	display: none;
}


}

</style>