<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package GDPR Cookie Hyva Compatibility (System)
 */

use Amasty\GdprCookieHyva\ViewModel\CookieGroupInfo;
use Amasty\GdprCookieHyva\ViewModel\Settings;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var Hyva\Theme\ViewModel\HyvaCsp|null $hyvaCsp */

$prefix = $block->getData('prefix');
$uniqueId = uniqid('_', false);
$refName = $prefix . CookieGroupInfo::REF_NAME;
$closeAction = $prefix . CookieGroupInfo::CLOSE_ACTION;
$openAction = $prefix . CookieGroupInfo::OPEN_ACTION;
$settings = $viewModels->require(Settings::class);
?>

<div x-data="initCookieGroupInfo<?= $escaper->escapeHtmlAttr($uniqueId) ?>" x-bind="eventListeners">
    <div x-cloak
         x-bind="overlay"
         class="fixed inset-0 flex items-center justify-center text-left bg-gray-500/50 z-50"
    >
        <div x-ref="<?= $escaper->escapeHtmlAttr($refName) ?>"
             role="dialog"
             aria-labelledby="amcookie-group-info"
             class="inline-block max-h-[92vh] max-w-[90vw] overflow-auto
                bg-ambar-info-bar-background shadow-xl rounded-lg p-8 text-gray-700 relative"
        >
            <template x-if="group">
                <div id="amcookie-group-info">
                    <button @click="closeHandler"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Close')) ?>"
                            class="absolute right-2 top-2 text-gray-300 transition
                                hover:text-black focus:drop-shadow-md hover:drop-shadow-md"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                             stroke="currentColor"
                             stroke-width="2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"/>
                        </svg>
                    </button>
                    <div class="md:flex md:justify-start pb-4">
                        <h3 class="text-xl font-semibold text-ambar-info-bar-title" x-text="group.name"></h3>
                    </div>
                    <template x-if="group.description">
                        <p class="mb-4 text-ambar-info-bar-description" x-html="group.description"></p>
                    </template>
                    <div class="overflow-x-scroll md:overflow-x-auto">
                        <table class="table-auto w-full mb-4 text-left">
                            <thead class="text-ambar-info-bar-table-header bg-gray-100">
                            <tr>
                                <th class="border px-4 py-3"><?= $escaper->escapeHtml(__('Cookie Name')) ?></th>
                                <th class="border px-4 py-3"><?= $escaper->escapeHtml(__('Cookie Provider')) ?></th>
                                <th class="min-w-[30%] border px-4 py-3"><?= $escaper->escapeHtml(__('Cookie Description')) ?></th>
                                <th class="border px-4 py-3"><?= $escaper->escapeHtml(__('Cookie Lifetime')) ?></th>
                                <th class="border px-4 py-3"><?= $escaper->escapeHtml(__('Cookie Type')) ?></th>
                            </tr>
                            </thead>
                            <tbody class="text-ambar-info-bar-table-content">
                            <template x-for="(item, index) in group.cookies" :key="index">
                                <tr>
                                    <td x-text="item.name" class="font-semibold border px-4 py-3"></td>
                                    <td x-text="item.provider" class="border px-4 py-3"></td>
                                    <td x-html="item.description" class="min-w-[30%] border px-4 py-3"></td>
                                    <td x-text="item.lifetime" class="border px-4 py-3"></td>
                                    <td x-text="item.type" class="border px-4 py-3"></td>
                                </tr>
                            </template>
                            </tbody>
                        </table>
                    </div>
                </div>
            </template>
            <button
                @click="closeHandler"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Done')) ?>"
                class="mt-4 w-auto bg-[#3B7E48] hover:bg-[#E63833] group-hover:bg-[#E63833] text-white text-xs  md:text-base font-normal px-8 py-3 rounded-full transition-all duration-300 ease-in-out hover:scale-105 hover:shadow-xl uppercase"
            >
                <?= $escaper->escapeHtml($settings->getCookieInformationBarDoneButtonText()) ?>
            </button>
        </div>
    </div>

</div>
<script data-cfasync="false">
    'use strict';

    function initCookieGroupInfo<?= /* @noEscape */ $uniqueId ?>() {
        return {
            ...hyva.modal({
                dialog: '<?= $escaper->escapeHtml($refName) ?>'
            }),
            group: null,
            eventListeners: {
                ['@<?= /* @noEscape */ $closeAction ?>.window']() {
                    this.closeHandler();
                },
                ['@<?= /* @noEscape */ $openAction ?>.window'](event) {
                    this.group = event.detail;

                    if (!!this.group) {
                        /*
                         If modal have big cookies list this can lead to
                         trigger hide event in hyva.modal.eventListeners.click,
                         so we should wait till this.group is reassigned
                         */
                        this.$nextTick(() => this.show('<?= $escaper->escapeHtml($refName) ?>'));
                    }
                }
            },
            closeHandler: function () {
                this.hide('<?= $escaper->escapeHtml($refName) ?>');
            }
        }
    }

    window.addEventListener(
        'alpine:init',
        () => Alpine.data(
            'initCookieGroupInfo<?= /* @noEscape */ $uniqueId ?>',
            initCookieGroupInfo<?= /* @noEscape */ $uniqueId ?>
        ),
        {once: true}
    );
</script>
<?php isset($hyvaCsp) && $hyvaCsp->registerInlineScript() ?>
