<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Customer\Block\Account\Resetpassword;
use Magento\Framework\Escaper;

/** @var Resetpassword $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$heroicons = $viewModels->require(HeroiconsSolid::class);
$minimumPasswordLength = $block->getMinimumPasswordLength();
$passwordMinCharacterSets = $block->getRequiredCharacterClassesNumber();
?>
<div class="forgot-password text-center my-12">
<div class="shadow-none">
    <div class="block block-customer-login bg-white inline-block py-[21px] px-2 md:px-[35px] border-[10px] border-[#f8f8f8] shadow-[3px_3px_3px_3px_rgba(0,0,0,0.1)] w-full md:w-[540px]">
        <form action="<?= $escaper->escapeUrl(
            $block->getUrl(
                '*/*/resetpasswordpost',
                ['_query' => ['id' => $block->getRpCustomerId(), 'token' => $block->getResetPasswordLinkToken()]]
            )
        ) ?>"
              x-data="Object.assign(hyva.formValidation($el), {showPassword: false, showPasswordConfirm: false})"
              @submit="onSubmit"
              method="post"
              id="form-validate"
              class="form password reset">
            <fieldset class="fieldset">
                <?= $block->getBlockHtml('formkey'); ?>
                <div class="field field-reserved required text-left mb-6">
                    <label class="label" for="password">
                        <span><?= $escaper->escapeHtml(__('New Password')) ?></span>
                    </label>
                    <div class="control flex items-center relative">
                        <input :type="showPassword ? 'text' : 'password'" type="password"
                               class="form-input w-full bg-[#E4F0E8] border-[#E4F0E8] rounded-none h-12" name="password" id="password" required
                               minlength="<?= $escaper->escapeHtmlAttr($minimumPasswordLength) ?>"
                               @input="onChange"
                               data-validate='{"password-strength": {"minCharacterSets": <?= (int) $passwordMinCharacterSets ?>}}'
                               autocomplete="<?= $block->isAutocompleteDisabled() ? 'off' : 'new-password' ?>"
                        />
                        <div x-on:click="showPassword = !showPassword"
                             class="cursor-pointer px-4 py-3 absolute right-0"
                             :aria-label="showPassword ? '<?= $escaper->escapeJs(__('Hide Password')) ?>' : '<?= $escaper->escapeJs(__('Show Password')) ?>'"
                        >
                            <template x-if="!showPassword">
                                <?= $heroicons->eyeHtml('', 20, 20, ['aria-hidden' => 'true']); ?>
                            </template>
                            <template x-if="showPassword">
                                <?= $heroicons->eyeOffHtml('', 20, 20, ['aria-hidden' => 'true']); ?>
                            </template>
                        </div>
                    </div>
                </div>
                <div class="field field-reserved text-left mb-6">
                    <label class="label" for="password-confirmation">
                        <span><?= $escaper->escapeHtml(__('Confirm New Password')) ?></span>
                    </label>
                    <div class="control flex items-center relative">
                        <input :type="showPasswordConfirm ? 'text' : 'password'" type="password"
                               class="form-input w-full bg-[#E4F0E8] border-[#E4F0E8] rounded-none h-12" name="password_confirmation"
                               id="password-confirmation"
                               data-validate='{"equalTo": "password"}'
                               @input="onChange"
                               autocomplete="<?= $block->isAutocompleteDisabled() ? 'off' : 'new-password' ?>"
                        />
                        <div x-on:click="showPasswordConfirm = !showPasswordConfirm"
                             class="cursor-pointer px-4 py-3 absolute right-0"
                             :aria-label="showPasswordConfirm ? '<?= $escaper->escapeJs(__('Hide Password')) ?>' : '<?= $escaper->escapeJs(__('Show Password')) ?>'"
                        >
                            <template x-if="!showPasswordConfirm">
                                <?= $heroicons->eyeHtml('', 20, 20, ['aria-hidden' => 'true']); ?>
                            </template>
                            <template x-if="showPasswordConfirm">
                                <?= $heroicons->eyeOffHtml('', 20, 20, ['aria-hidden' => 'true']); ?>
                            </template>
                        </div>
                    </div>
                </div>
            </fieldset>
            <div class="flex justify-between pt-8 pb-2 !border-0"> 
                    <button type="submit" class="bg-[#3B7E48] hover:bg-[#E63833] group-hover:bg-[#E63833] text-white text-xs  md:text-base font-normal px-2 py-3 rounded-full transition duration-400 uppercase px-8"><span><?= $escaper->escapeHtml(__('Set a New Password')) ?></span></button>
                
            </div>
        </form>
    </div>
</div>
</div>