<?php

declare(strict_types=1);

/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop by Brand Subscription Functionality Hyva
 */

use Amasty\ShopByBrandSubscriptionFunctionality\Block\Widget\BrandInfo;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;

/**
 * @var Escaper $escaper
 * @var HeroiconsSolid $heroicons
 * @var BrandInfo $block
 * @var ViewModelRegistry $viewModels
 */

$heroicons = $viewModels->require(HeroiconsSolid::class);

?>
<?php if ($block->isProductPage()): ?>
    <?php foreach ($block->getBrands() as $brand): ?>
        <?php
        $showBrandDescription = $block->shouldShowBrandDescription($brand);
        $showBrandInfo = $block->shouldShowBrandInfo($brand);
        ?>
        <?php if ($showBrandDescription || $showBrandInfo): ?>
            <div class="ambrand-widget-brand-info max-w-xl">
                <span class="ambrand-widget-title"><?= $escaper->escapeHtml(__($brand->getTitle())) ?>:</span>
                <?php if ($showBrandDescription): ?>
                    <p class="ambrand-widget-description"><?= $escaper->escapeHtml(__($brand->getShortDescription()), ['u', 'b', 'i', 'br', 'a']) ?></p>
                <?php endif; ?>
                <?php if ($showBrandInfo): ?>
                    <div class="ambrand-info flex mb-8 sm:px-0">
                        <div class="min-w-sm"><?= $heroicons->informationCircleHtml('mr-2 fill-blue-500', 24, 24) ?></div>
                        <div class="ambrand-info-values">
                            <?php foreach ($block->getBrandInfoValues($brand) as $brandInfoValue): ?>
                                <p class="ambrand-info-value mb-0"><?= $escaper->escapeHtml($brandInfoValue, ['u', 'b', 'i', 'br', 'a']) ?></p>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php endif; ?>
                <hr class="ambrand-widget-hr mb-4 mt-2">
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
