<style type="text/css">

    #sagepaysuite-version-container {
        background: #f8f8f8;
        border: 1px solid #e3e3e3;
        padding: 1.5rem;
    }

    #sagepaysuite-version-container h2 {
        color:#EA7601;
        font-weight: bold;
        margin-bottom: 5px;
    }

    #sagepaysuite-version-container p {
        font-size: 12px;
    }

    #sagepaysuite-version-container a.signUpLink {
        font-size: 12px;
        background-color:#EA7601;
        color:white;
        padding-left: 4px;
        padding-right: 4px;
    }

    #sagepaysuite-version-container a.signUpLink:hover {
        text-decoration: none;
    }

</style>

<div id="sagepaysuite-version-container">
    <img style="margin-bottom: 10px; width: 250px" src="https://ebizmarts-website.s3.amazonaws.com/Logo_Ebizmarts.png"/>
    <h2>ebizmarts Payment Suite 10 (with SagePay, Opayo, and Elavon Support) <?= $block->escapeHtml($block->getVersion())?></h2>
    <p>
        <a target="_blank" href="https://ebizmarts.com"><b>ebizmarts</b></a> <?= $block->escapeHtml(__('is an Opayo approved partner')) ?>.
        <a target="_blank" href="https://referrals.elavon.co.uk/?partner_id=0014H00004E0itk" class="signUpLink"><?= $block->escapeHtml(__('Get an Opayo Account Now!')) ?></a>
    </p>
    <p>Need assistance?
        <a target="_blank" href="mailto:sagepay@ebizmarts-desk.zendesk.com"><?= $block->escapeHtml(__('Submit a ticket')) ?></a>
    </p>
    <p>Got feedback?
        <a target="_blank" href="mailto:support@ebizmarts-desk.zendesk.com"><?= $block->escapeHtml(__('Email us')) ?></a> or
        <a target="_blank" href="https://store.ebizmarts.com/subscribe-to-our-newsletter"><?= $block->escapeHtml(__('Subscribe to our newsletter')) ?></a>
    </p>
    <p>
        <table cellspacing="0" cellpadding="0" border="0">
            <tr>
                <td style="width: 50px; padding:0rem; vertical-align: inherit"><img style="display: block height: 32px; width: 50px" src="https://ebizmarts-website.s3.amazonaws.com/Logo_ApplePay.svg"></td>
                <td style="width: 75px; padding:0rem; vertical-align: inherit"><img style="display: block height: 52px; width: 75px" src="https://ebizmarts-website.s3.amazonaws.com/Logo_GooglePay.svg"></td>
                <td style="text-align:left; padding:0rem; vertical-align: inherit">
                    <?= $block->escapeHtml(__('Now Available! ')) ?>
                    <a target="_blank" href="mailto:payments@ebizmarts-desk.zendesk.com?Subject=Ebizmarts Payments <?= $block->escapeHtml($block->getVersion())?>"><?= $block->escapeHtml(__('Contact Us')) ?></a>
                    <?= $block->escapeHtml(__(' for more info.')) ?>
                </td>
            </tr>
        </table>
    </p>
</div>
