<?php
/**
 * Copyright © 2017 ebizmarts. All rights reserved.
 * See LICENSE.txt for license details.
 */

$_code = $block->getMethodCode();
// phpcs:disable
$_config = $this->helper('Ebizmarts\SagePaySuite\Helper\Data')->getSagePayConfig();
// phpcs:enable
?>


<div id="payment_form_<?= $block->escapeHtmlAttr($_code) ?>" class="admin__page-section-item" style="display:none;"
    data-mage-init='{"sagepaysuiteRepeatForm":{
            "url": {
                "request" : "<?= $block->escapeHtml($block->getUrl('sagepaysuite/repeat/request', [])); ?>"
            },
            "mode": "<?= $block->escapeHtml($_config->getMode()); ?>"
}}'>

    <span id="<?= $block->escapeHtmlAttr($_code) ?>-payment-errors" class="message error" style="display: none;"></span>

    <fieldset class="admin__fieldset">
    <div class="admin__field">
        <label 
                class="label admin__field-label" 
                for="<?= $block->escapeHtmlAttr($_code) ?>_vpstxid"
        >
            <?= $block->escapeHtml(__('VPSTxId')) ?>
            <span class="required">*</span>
        </label>
        <div class="admin__field-control control">
            <input 
                type="text" 
                id="<?= $block->escapeHtmlAttr($_code) ?>_vpstxid" 
                title="<?= $block->escapeHtmlAttr(__('VPSTxId')) ?>" 
                class="input-text admin__control-text" 
                value="" 
            />
        </div>
    </div>
    </fieldset>
</div>