<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop By Hyva Compatibility
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Amasty\Shopby\Block\Navigation\Widget\FromTo;
use Amasty\ShopbyBase\Model\FilterSetting;
use Amasty\ShopbyHyvaCompatibility\ViewModel\ProductListAjax;

/** @var Escaper $escaper */
/** @var FromTo $block */
/** @var ViewModelRegistry $viewModels */
/** @var FilterSetting $filterSetting */

/** @var ProductListAjax $productListAjax */
$productListAjax = $viewModels->require(ProductListAjax::class);

$uniqId = "_" . uniqid();
$filterCode = $escaper->escapeHtml($filterSetting->getAttributeCode());
$min = $escaper->escapeHtml($fromToConfig['min']);
$max = $escaper->escapeHtml($fromToConfig['max']);
$from = $fromToConfig['from'];
$to = $fromToConfig['to'];
$step = $fromToConfig['step'];
$fromToType = $block->getWidgetType();
$hideDigitsAfterDot = $filterSetting->getHideZeros();
$filterMode = $filterSetting->getDisplayMode();
$isShowOnlyWidget = $filterSetting->getDisplayMode() === 0 || $filterSetting->getDisplayMode() === 3;
$expandedMode = $filterSetting->getData('is_expanded');
$filterName = $block->getFilter()->getName();
// phpcs:disable Generic.Files.LineLength.TooLong
?>
<div id="am-filter-widget-<?= /* @noEscape */ $filterCode . $uniqId ?>"
     class="amshopby-fromto-wrap filter-option mt-4 am-filter-items-<?= /* @noEscape */ $filterCode ?>
     <?= $escaper->escapeHtmlAttr($isShowOnlyWidget ? 'am-filter mt-4' : ''); ?>"
     data-am-js="fromto-widget"
     x-data="<?= $isShowOnlyWidget ? 'initRanges' . $escaper->escapeJs($uniqId) . '()' : '' ?>"
     x-init="<?= $isShowOnlyWidget ? 'amShopbyFilterRanges($el)' : '' ?>"
    <?= $isShowOnlyWidget ? "data-amshopby-expanded='" . $escaper->escapeHtml($expandedMode ?? '0') . "'" : '' ?>
>
    <form data-amshopby-filter="<?= /* @noEscape */ $filterCode ?>"
          data-amshopby-filter-request-var="<?= /* @noEscape */ $block->getFilter()->getRequestVar() ?>"
          :aria-label="ariaText"
          <?= $from || $to ? 'class="amshopby-link-selected text-black"' : '' ?>>
        <input :value="currentInputValues"
               type="hidden"
               data-amshopby-fromto="value"
               data-digits-after-dot="<?= /* @noEscape */ $hideDigitsAfterDot ? '1' : '0' ?>"
               name="amshopby[<?= $escaper->escapeHtml($block->getFilter()->getRequestVar()) ?>][]"/>
        <div class="range am-fromto-widget amshopby_currency_rate flex flex-wrap justify-center px-4"
             data-rate="<?= /* @noEscape */ $fromToConfig['curRate'] ?>">
            <div class="amshopby-input-wrapper flex-grow relative"
                 role="group"
                 aria-labelledby="fromfield-id-<?= $escaper->escapeJs($uniqId) ?>"
            >
                <input class="am-filter-price -from input-text form-input text-center appearance-none w-full"
                       data-amshopby-fromto="from"
                       type="number"
                       id="fromfield-id-<?= $escaper->escapeJs($uniqId) ?>"
                       aria-label="<?= $escaper->escapeHtmlAttr(__('From')) ?>"
                       placeholder="<?= $escaper->escapeHtmlAttr(__('From')) ?>"
                       x-ref="widgetMin"
                       :value="widgetMinValue"
                    <?php if ($block->collectFilters()): ?>
                        @input.debounce.250ms="calcWidgetMin($refs.widgetMin);setValue('min')"
                    <?php else: ?>
                        @input.debounce.250ms="calcWidgetMin($refs.widgetMin)"
                    <?php endif; ?>
                       :min="options.min"
                       :max="options.max"
                />
                <span class="amshopby-currency absolute bg-white -top-3 left-2"><?= $escaper->escapeHtml($fromToConfig['currencySymbol']) ?></span>
            </div>
            <span class="delimiter flex justify-center items-center px-2">-</span>
            <div class="amshopby-input-wrapper flex-grow"
                 role="group"
                 aria-labelledby="tofield-id-<?= $escaper->escapeJs($uniqId) ?>"
            >
                <input class="am-filter-price -to input-text form-input text-center appearance-none w-full"
                       data-amshopby-fromto="to"
                       type="number"
                       id="tofield-id-<?= $escaper->escapeJs($uniqId) ?>"
                       aria-label="<?= $escaper->escapeHtmlAttr(__('To')) ?>"
                       placeholder="<?= $escaper->escapeHtmlAttr(__('To')) ?>"
                       x-ref="widgetMax"
                       :value="widgetMaxValue"
                    <?php if ($block->collectFilters()): ?>
                        @input.debounce.250ms="calcWidgetMax($refs.widgetMax);setValue('max');"
                    <?php else: ?>
                        @input.debounce.250ms="calcWidgetMax($refs.widgetMax)"
                    <?php endif; ?>
                       :min="options.min"
                       :max="options.max"
                />
            </div>
            <?php if (!$block->collectFilters()): ?>
                <button type="button"
                        data-amshopby-fromto="go"
                        @click.prevent.stop="applyFilter()"
                        class="am-filter-go btn btn-primary w-full justify-center mt-4"
                        title="<?= $escaper->escapeHtmlAttr(__('Apply filter')) ?>">
                    <?= $escaper->escapeHtml(__('Apply')) ?>
                </button>
            <?php endif; ?>
        </div>
    </form>
</div>

<?php if ($isShowOnlyWidget): ?>
    <script>
        function initRanges<?= $escaper->escapeJs($uniqId) ?>() {
            return deepMerge({}, initRanges(), {
                options: {
                    collectFilters: <?= /* @noEscape */ $block->collectFilters() ?>,
                    template: "<?= $escaper->escapeHtml($fromToConfig['template']) ?>",
                    currencySymbol: "<?= $escaper->escapeHtml($fromToConfig['currencySymbol']) ?>",
                    currencyPosition: "<?= $escaper->escapeHtml($fromToConfig['currencyPosition']) ?>",
                    step: <?= /* @noEscape */ $escaper->escapeHtml(floatval($fromToConfig['step'])) ?>,
                    from: "<?= /* @noEscape */ $fromToConfig['from'] ?>",
                    to: "<?= /* @noEscape */ $fromToConfig['to'] ?>",
                    deltaFrom: "<?= /* @noEscape */ $fromToConfig['deltaFrom'] ?>",
                    deltaTo: "<?= /* @noEscape */ $fromToConfig['deltaTo'] ?>",
                    curRate: "<?= /* @noEscape */ $fromToConfig['curRate'] ?>",
                    min: <?= (float)$min ?>,
                    max: <?= (float)$max ?>,
                    url: "<?= /* @noEscape */ $block->getSliderUrlTemplate() ?>",
                    code: "<?= $escaper->escapeHtml($filterSetting->getAttributeModel()->getAttributeCode()) ?>",
                    isAddFromWidget: <?= /* @noEscape */ $filterSetting->getAddFromToWidget() ? "1" : '0' ?>,
                    hideDigitsAfterDot: <?= /* @noEscape */ $hideDigitsAfterDot ? '1' : '0' ?>
                },
                code: '<?= $escaper->escapeHtmlAttr($block->getFilter()->getRequestVar()) ?>',
                uniqId: '<?= /* @noEscape */ $uniqId; ?>',
                filterCode: '<?= $escaper->escapeHtmlAttr($filterCode) ?>',
                filterName: '<?= $escaper->escapeHtmlAttr($filterName); ?>',
                ariaText: '<?= $escaper->escapeHtml(__('Filter %1 in sidebar', $filterName)) ?>',
                isAjax: <?= (int)$productListAjax->isAjaxSettingEnabled(); ?>,
                rangesElement: false,
                currentInputValues: '',

                /**
                 *
                 * @param element
                 */
                amShopbyFilterRanges(element) {
                    this.filterWrapperCheck(element);
                    this.rangesElement = element;
                    this.currentMin = this.options.from && this.options.from >= this.options.min
                        ? this.options.from
                        : this.options.min;
                    this.currentMax = this.options.to && this.options.to <= this.options.max
                        ? this.options.to
                        : this.options.max;

                    this.currentMin = this._parseValue(this.currentMin);
                    this.currentMax = this._parseValue(this.currentMax);

                    this.widgetMinValue = this._parseValue(this.currentMin * +this.options.curRate);
                    this.widgetMaxValue = this._parseValue(this.currentMax * +this.options.curRate);

                    if (this.options.to || this.options.from) {
                        this.currentInputValues = this._parseValue(this.options.from)
                            + "-" + this._parseValue(this.options.to);
                    }

                    this.generateValues();
                },

                /**
                 *
                 * @param el
                 */
                calcWidgetMin(el) {
                    this.currentMin = el.value / +this.options.curRate;
                    this.widgetMinValue = this._parseValue(this.currentMin * +this.options.curRate);
                    this.generateValues();
                },

                /**
                 *
                 * @param el
                 */
                calcWidgetMax(el) {
                    this.currentMax = el.value / +this.options.curRate;
                    this.widgetMaxValue = this._parseValue(this.currentMax * +this.options.curRate);
                    this.generateValues();
                },

                /**
                 *
                 * @param flag
                 */
                setValue(flag) {
                    this.currentInputValues = this._parseValue(this.currentMin)
                        + "-" + this._parseValue(this.currentMax);
                    window.dispatchEvent(new CustomEvent('amSetButtonPosition', {detail: {element: this.rangesElement}}));
                    switch (flag) {
                        case 'min':
                            if (parseFloat(this.currentMin) > parseFloat(this.options.min)) {
                                this.applyFilter();
                            }
                            break;
                        case 'max':
                            if (parseFloat(this.currentMax) > parseFloat(this.options.min)) {
                                this.applyFilter();
                            }
                            break;
                    }
                },

                /**
                 *
                 */
                applyFilter() {
                    document.querySelectorAll(
                        '.price-ranges input[type="radio"], .price-ranges input[type="checkbox"]'
                    ).forEach(input => {
                        input.checked = false;
                    });

                    if (this.isAjax) {
                        this._dispatchEventsForAjax(this._generateSearchHref());
                    } else {
                        window.location.href = this._generateSearchHref();
                    }
                },

                /**
                 *
                 * @param searchParams
                 * @private
                 */
                _dispatchEventsForAjax(searchParams) {
                    const { to, from } = this.options;

                    this.currentInputValues = (this.currentMin === Number(to) && this.currentMax === Number(from))
                        ? ''
                        : `${this._parseValue(this.currentMin)}-${this._parseValue(this.currentMax)}`;

                    window.dispatchEvent(new CustomEvent('amSliderValuesUpdated', {
                        detail: {
                            searchParams: searchParams,
                            values: this.currentInputValues,
                            element: this.$el.closest('.range')
                        }
                    }));
                }
            })
        }
    </script>
<?php endif; ?>
