<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package Shop By Hyva Compatibility
 */
?>
<?php
use Magento\Framework\Escaper;
use Amasty\Shopby\Block\Navigation\Widget\Tooltip;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/** @var Escaper $escaper */
/** @var Tooltip $block */
/** @var ViewModelRegistry $viewModels */

/** @var Hyva\Theme\ViewModel\HeroiconsSolid $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$content = $block->getContent();
$uniqueId = uniqid();
// phpcs:disable Generic.Files.LineLength.TooLong
?>
<?php if ($content): ?>
    <script>
      function initFilterTooltip_<?= $escaper->escapeHtml($uniqueId); ?>() {
        return deepMerge({}, initFilterTooltip(), {
          content: <?= /* @noEscape */ $block->jsonEncode($content) ?>,
          tooltipImage: <?= /* @noEscape */ $block->jsonEncode($block->getTooltipUrl(24, 24)) ?>,
        }, initSelectorsILN());
      }
    </script>
    <div class="am-filter-tooltip ml-2 mr-3 order-1 inline-flex w-6 h-6"
         x-init="moveToTitle($el)"
         x-data="initFilterTooltip_<?= $escaper->escapeHtml($uniqueId); ?>">

        <span class="cursor-pointer"
              @mouseenter.self="showTooltip = true; loadTooltip()"
              @mouseleave.self="showTooltip = false">
            <template x-if="tooltipImage">
                <span class="tooltip amshopby-filter-tooltip block">
                    <img :src="tooltipImage" :alt="content" width="24px" height="24px" loading="lazy">
                </span>
            </template>
            <template x-if="!tooltipImage">
                <?= $heroicons->exclamationCircleHtml('w-6 h-6') ?>
            </template>
        </span>

        <template x-if="tooltipLoaded" x-teleport=".one-column-wrapper">
            <div x-show="showTooltip" class="shadow-lg">
                <div x-ref="tooltip" :style="{
                    'top': top + 'px',
                    'left': left + 'px'
                }" class="fixed top-0 z-10 w-64 -mt-6 p-4 text-sm text-black leading-tight bg-white rounded-lg shadow-xl">
                    <span class="subtitle text-base" x-html="content"></span>
                    <svg class="absolute left-1/3 z-10 w-8 h-8 text-white fill-current stroke-current
                    transform -translate-x-1/4 translate-y-1/4 md:translate-y-1/4" width="12" height="12">
                        <rect x="12" y="-12" width="12" height="12" transform="rotate(45)" class="shadow-xl"/>
                    </svg>
                </div>
            </div>
        </template>
    </div>
<?php endif; ?>
