<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
$width = (int)$block->getBackgroundImageWidth() ?: 700;
$imageHelper = $this->helper(\Magefan\Blog\Helper\Image::class);
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="post-list-wrapper blog-widget-recent">
    <h3 class="title"><?= $block->escapeHtml($block->getTitle()) ?></h3>
    <ul class="post-list clearfix">
        <?php foreach ($_postCollection as $_post) { ?>
            <?php
                $_postUrl = $block->escapeUrl($_post->getPostUrl());
                $_postName = $block->escapeHtml($_post->getTitle());
            ?>
            <li class="post-holder post-holder-<?= (int)$_post->getId() ?>">
                <div class="post-header">
                    <div class="post-info clear">                      
                        <!-- <?//php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                        <div class="item post-categories">
                            <span class="label"><?//= $block->escapeHtml(__('Categories:')) ?></span>
                            <?//php $n = 0;
                            //foreach ($_post->getParentCategories() as $ct) { $n++; ?>
                                <a title="<?//= $block->escapeHtml($ct->getTitle()) ?>"
                                   href="<?//= $block->escapeUrl($ct->getCategoryUrl()) ?>">
                                    <?//= $block->escapeHtml($ct->getTitle()) ?>
                                </a>
                                <?//php if ($n != $_categoriesCount) { ?>, <?//php } ?>
                            <?//php } ?>
                        </div>
                        <?//php } ?> -->
                    </div>
                </div>

                <div class="post-content">
                    <div class="post-description clearfix">
                        <?php $featuredImage = $_post->getFeaturedListImage() ?: $_post->getFeaturedImage(); ?>
                        <?php if ($featuredImage) { ?>
                            <?php
                                $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                            if (!$featuredImgAlt) {
                                $featuredImgAlt = $_postName;
                            }
                            ?>
                            <div class="post-image">
                            <!-- img container -->
                            <div class="image-container">
                                <a class="image-wrap" href="<?= /*@noEscape*/ $_postUrl ?>" title="<?= /*@noEscape*/ $_postName ?>">
                                    <?php $featuredImage = $_post->getFeaturedListImg() ?: $_post->getFeaturedImg(); ?>
                                    <?php
                                    if (!$featuredImage) {
                                        $featuredImage = $this->getViewFileUrl('Magefan_Blog::images/default-no-image.png');
                                    }
                                    ?>
                                    <?php if ($featuredImage) { ?>
                                        <?php
                                        $featuredImage = $imageHelper->init($featuredImage)->resize($width, null, false);
                                        $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                        if (!$featuredImgAlt) {
                                            $featuredImgAlt = $_postName;
                                        }
                                        ?>
                                        <div class="animation-type-zoom bg-img mfblogunveil" data-original="<?= $block->escapeHtml($featuredImage) ?>"></div>
                                        <?php /* <img class="" src="<?= $block->escapeHtml($featuredImage) ?>" alt=""> */ ?>
                                    <?php } ?>
                                </a>

                                <!-- post category-->
                               <!--  <?php //if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                                    <span class="post-category">
                                        <?//php foreach ($_post->getParentCategories() as $ct) { ?>
                                            <a class="category-name" href="<?//= $block->escapeUrl($ct->getCategoryUrl()) ?>"
                                               title="<?//= $block->escapeHtml($ct->getTitle()) ?>">
                                                <?//= $block->escapeHtml($ct->getTitle()) ?>
                                            </a>
                                        <?//php } ?>
                                    </span>
                                <?//php }  ?> -->
                                <!-- end post category-->
                            </div>
                        </div>
                        <?php } ?>

                        <div class="post-details">
                            <?php if ($_post->isPublishDateEnabled()) { ?>
                                <div class="item post-posed-date">
                                    <!-- <span class="label"><?//= $block->escapeHtml(__('Posted:')) ?></span> -->
                                    <span class="value"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                                </div>
                            <?php } ?>

                            <div class="post-title-holder clearfix">
                                <div class="post-title">
                                    <a class="post-item-link"
                                       href="<?= /*@noEscape*/ $_postUrl ?>">
                                        <?= /*@noEscape*/ $_postName ?>
                                    </a>
                                </div>
                            </div>

                             <div class="post-text-hld clearfix">
                                <?= /*@noEscape*/ $block->getShorContent($_post) ?>
                            </div>
                            <!-- <a class="post-read-more"
                               href="<?= /*@noEscape*/ $_postUrl ?>"
                               title="<?= /*@noEscape*/ $_postName ?>"
                               >
                               <?//= $block->escapeHtml(__('CONTINUE READING')) ?>
                            </a> -->
                        </div>
                    </div>
                </div>
                <div class="post-footer">

                </div>
            </li>

        <?php } ?>
    </ul>
</div>
<?php } ?>