<?php
/**
 * Store Locator - Full Working Layout
 */

use Amasty\Storelocator\Block\Location;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\Model\ViewModelRegistry;

/**
 * @var \Amasty\Storelocator\Block\Location $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Hyva\Theme\ViewModel\HeroiconsOutline $heroicons
 * @var \Hyva\Theme\Model\ViewModelRegistry $viewModels
 */

$productId = (int)$block->getRequest()->getParam('product');
$attributes = $block->getAttributes();
$heroicons = $viewModels->require(HeroiconsOutline::class);
$googleMapId = $block->getMapId();
$custom = $viewModels->require(\Haartyhanks\RemoveObjectManager\ViewModel\Custom::class);
if ($productId):
    $product = $block->getProductById($productId);
?>
    <h1>
        <?= $escaper->escapeHtml($product->getName()); ?>
        <?= $escaper->escapeHtml(__(' can be found at the following stores:&nbsp;')); ?>
    </h1>
    <hr>
<?php endif; ?>

<div
    x-data="storeLocator()"
    class="amlocator-main-container flex flex-col w-full gap-4 px-6 md:px-0"
    @map-loaded.window="initStoreLocator()"
>

    <!-- Search Bar on Top -->
    <?php if ($block->getShowSearch()): ?>
        <div class="w-full text-left md:text-center  lg:w-[930px] mx-auto">
            <?= $block->getSearchHtml(); ?>
        </div>
    <?php endif; ?>

    <div class="bg-[#F5F9F7] py-6 md:py-12 pb-0">
    <div class="flex flex-col md:flex-row w-full gap-4  lg:w-[930px] mx-auto">
        <!-- Left Column: Filters + Store List -->
        <div class="flex flex-col h-[320px] mb-6 md:mb-0 md:w-1/3 gap-2 md:h-[535px]">

            <!-- Filters Sticky -->
            <?php $extraFiltersHtml = $block->getChildHtml('extra_filters'); ?>
           

            <!-- Scrollable Store List -->
            <div id="amlocator-store-list" class="amlocator-store-list overflow-auto flex-1 " x-ref="storeList" >
                <?= $block->getLeftBlockHtml(); ?>
            </div>
        </div>

        <!-- Right Column: Map -->
        <div class="amlocator-map w-full h-[300px] md:pl-4 md:w-2/3 md:h-[535px] md:pb-0">
            <div
                id="<?= $escaper->escapeHtml($googleMapId); ?>"
                class="relative w-full h-full overflow-hidden"
            ></div>
        </div>
    </div>
</div>
</div>

<?= $block->getJsBlockHtml(); ?>

<?php
$placeholderImage = $custom->getMediaUrl().'catalog/product/placeholder/default/no-image_5.jpg';
 $allLocations = $block->getLocationCollection()
    ->addFieldToSelect('*') 
    ->addFieldToFilter('status', 1) 
    ->setOrder('id', 'DESC');
   $allLocations->load();
$allItems = $allLocations->getItems();

usort($allItems, function($a, $b) {
    return $b->getId() - $a->getId(); 
});
$locations = array_slice($allItems, 0, 3);
?>

<div class="w-full lg:w-[1200px] lg:px-6 mx-auto py-12 px-4 md:px-0">
    <h2 class="text-2xl text-black font-bold lg:text-[38px] lg:leading-[44px] mb-10 text-center">Say Hello To Our Newest Store</h2>
<div class="grid grid-cols-1 md:grid-cols-3 gap-10">
  
    <?php foreach ($locations as $location): 
       $imageUrl = $block->getLocationImage($location);
        if (!$imageUrl) {
            $imageUrl = $placeholderImage;
        }
    ?>
    <div class="bg-white rounded-lg transition overflow-hidden">
        <!-- Image -->
       <a href="<?= $block->getUrl('amlocator/' . $location->getUrlKey()) ?>" target="blank">
        <div class="w-full h-48 bg-center bg-cover rounded-xl border border-[#ddd]" style="background-image:url('<?= $imageUrl ?>')"></div>
       </a>

        <!-- Store info -->
        <div class="py-4 text-left">
            <a href="<?= $block->getUrl('amlocator/' . $location->getUrlKey()) ?>" target="blank">
            <h3 class="text-lg font-semibold text-black text-[22px]"><?= $location->getName() ?></h3>
        </a>
            <p class="text-black text-sm mt-2"><?= $location->getAddress()?><br><?= $location->getCity()?>, <?= $location->getZip()?></p>
             <?php if ($location->getPhone()):?>
              <p class="text-black text-sm mt-2">Tel: <?= $location->getPhone()?></p>
              <?php endif; ?>
                     <?php if ($location->getEmail()):?>
              <p class="text-black text-sm mt-1">Email: <?= $location->getEmail()?></p>
                 
                     <?php endif; ?>
        </div>
    </div>
    <?php endforeach; ?>
</div>
</div>