<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Blog post list template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList
 */
?>
<?php
$_postCollection = $block->getPostCollection();
$width = (int)$block->getBackgroundImageWidth() ?: 350;
$imageHelper = $this->helper(\Magefan\Blog\Helper\Image::class);
?>
<?php if (!$_postCollection->count()): ?>
    <div class="message info empty">
        <div>
            <?= $block->escapeHtml(__('We can\'t find posts matching the selection.')) ?>
        </div>
    </div>
<?php else: ?>

    <?= $block->getStyleViewModel()->getStyle('Magefan_Blog::css/bootstrap-4.4.1-custom-min.css') ?>
    <?= $block->getAdditionalHtml() ?>
    <div class="post-list-wrapper mt-12">
        <?php $iterator = 1; ?>
        <ol class="post-list modern">
            <?php foreach ($_postCollection as $_post): ?>
                <?php
                    $_postUrl = $block->escapeUrl($_post->getPostUrl());
                    $_postName = $block->escapeHtml($_post->getTitle());
                ?>
                <li class="post-item post-holder post-holder-<?= (int)$_post->getId() ?> flex flex-col lg:flex-row items-center mb-6 md:mb-12 lg:mb-16 group">

                   
                        <!-- post image -->
                        <div class="post-ftimg-hld w-full lg:w-[440px] lg:flex-[0_0_440px] w-full lg:h-[264px] lg:group-odd:order-1 lg:group-even:order-2 overflow-hidden relative">
                            <!-- img container -->
                            
                                <a class="block w-full h-full"
                                   style="line-height:0;padding-bottom:70%;"
                                   href="<?= /*@noEscape*/ $_postUrl ?>"
                                   title="<?= /*@noEscape*/ $_postName ?>"
                                >
                                    <?php $featuredImage = $_post->getFeaturedListImg() ?: $_post->getFeaturedImg(); ?>
                                    <?php
                                        if (!$featuredImage) {
                                            $featuredImage = $this->getViewFileUrl('Magefan_Blog::images/default-no-image.png');
                                        }
                                    ?>
                                    <?php if ($featuredImage) { ?>
                                        <?php
                                        $featuredImage = $imageHelper->init($featuredImage)->resize($width, null, false);
                                        $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                        if (!$featuredImgAlt) {
                                            $featuredImgAlt = $_postName;
                                        }
                                        ?>
                                        <div class="animation-type-zoom bg-img mfblogunveil absolute block w-full h-full bg-cover bg-center overflow-hidden hover:scale-110 duration-300" data-original="<?= $block->escapeHtml($featuredImage) ?>"></div>
                                        <?php /* <img class="" src="<?= $block->escapeHtml($featuredImage) ?>" alt=""> */ ?>
                                    <?php } ?>
                                </a>

                               
                             
                        </div>

                        <!-- block info -->
                        <div class="post-header bg-white px-4 pt-4 lg:p-8 shadow-[0_0_70px_rgba(0,_0,_0,_0.11)] relative z-10 lg:group-odd:order-2 lg:group-even:order-1 lg:group-odd:ml-[-120px] lg:group-even:mr-[-100px] ">
                            <!-- post title -->
                            <div class="post-title-wrap mb-2">
                                <h2 class="post-title">
                                    <a class="inline-block text-lg md:text-xl font-medium font-sans hover:text-red duration-300" href="<?= /*@noEscape*/ $_postUrl ?>"><?= /*@noEscape*/ $_postName ?></a>
                                </h2>
                            </div>

                            <!-- block data -->
                            <div class="post-data-wrap text-xs mb-3">
                                <!-- post author -->
                                <?php if ($block->authorEnabled()) { ?>
                                    <?php if ($_author = $_post->getAuthor()) { ?>
                                        <span class="post-author-name">
                                            <?php if ($block->authorPageEnabled()) { ?>
                                                <a class="font-medium hover:text-red duration-300" title="<?= $block->escapeHtml($_author->getTitle()) ?>"
                                                   href="<?= $block->escapeUrl($_author->getAuthorUrl()) ?>"><?= $block->escapeHtml($_author->getTitle()) ?>
                                                </a>
                                            <?php } else { ?>
                                                <?= $block->escapeHtml($_author->getTitle()) ?>
                                            <?php } ?>
                                            <span>-</span>
                                        </span>
                                    <?php } ?>
                                <?php } ?>

                                <!-- post date -->
                                <?php if ($_post->isPublishDateEnabled()) { ?>
                                    <span class="post-date text-gray-700"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                                <?php } ?>

                                <!-- post view -->
                                <?php if ($block->viewsCountEnabled()) { ?>
                                    <?php if ($viewsCount = $_post->getViewsCount()) { ?>
                                        <span class="post-view float-right hidden md:block">
                                            <?= $block->escapeHtml($viewsCount)?>
                                        </span>
                                    <?php } ?>
                                <?php } ?>
                            </div>

                            <!-- post description -->
                            <div class="post-description mb-4 hidden md:block">
                                <?= /*@noEscape*/ $_post->getShortFilteredContent() ?>
                            </div>

                            <!-- read more -->
                            <div class="post-read-more hidden md:block">
                                <a class="post-read w-full bg-[#3B7E48] hover:bg-[#E63833] group-hover:bg-[#E63833] text-white text-xs  md:text-base  font-normal px-6 py-2.5 rounded-full transition duration-400"   href="<?= /*@noEscape*/ $_postUrl ?>" title="<?= /*@noEscape*/ $_postName ?>">
                                    <?= $block->escapeHtml(__('Read more')) ?> <span class="sr-only">blog information</span>
                                </a>
                            </div>
                        </div>
                     
                </li>
            <?php endforeach; ?>
            <li class="hidden">
                <script type="text/javascript">
                    if (window.addthis) {
                        addthis.toolbox('.addthis_toolbox');
                    }
                </script>
            </li>
        </ol>
    </div>

    <?= $block->getToolbarHtml() ?>
    <?= $block->getChildHtml('addthisJs'); ?>
<?php endif; ?>

<style>
    .post-view {
        display: block;
        background: #000;
        color: #fff;
        font-size: 10px;
        font-weight: 600;
        text-align: center;
        line-height: 11px;
        position: relative;
        top: -5px;
        padding: 4px 6px;
    }
    .post-view:after {
        position: absolute;
        bottom: -3px;
        left: 0;
        content: '';
        width: 0;
        height: 0;
        border-style: solid;
        border-width: 3px 3px 0 0;
        border-color: #000 transparent transparent;
    }
</style>
