<template x-if="segment.code === 'shipping' && quoteData.is_virtual === 0 && !!shippingMethod">
    <div class="flex justify-between py-2 text-lg text-black font-semibold">
        <div class="w-7/12 text-left md:w-auto"
             x-html="segment.title"
        ></div>
        <div class="w-5/12 text-right md:w-auto"
             x-text="hyva.formatPrice(segment.value)"
        ></div>
    </div>
</template>
